from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin import util


class BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, edge_storage_strategy=None, sort_on_compaction=None, oe_mutability=None, ie_mutability=None):  # noqa: E501
        """BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams - a model defined in OpenAPI

        :param edge_storage_strategy: The edge_storage_strategy of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.  # noqa: E501
        :type edge_storage_strategy: str
        :param sort_on_compaction: The sort_on_compaction of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.  # noqa: E501
        :type sort_on_compaction: bool
        :param oe_mutability: The oe_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.  # noqa: E501
        :type oe_mutability: str
        :param ie_mutability: The ie_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.  # noqa: E501
        :type ie_mutability: str
        """
        self.openapi_types = {
            'edge_storage_strategy': str,
            'sort_on_compaction': bool,
            'oe_mutability': str,
            'ie_mutability': str
        }

        self.attribute_map = {
            'edge_storage_strategy': 'edge_storage_strategy',
            'sort_on_compaction': 'sort_on_compaction',
            'oe_mutability': 'oe_mutability',
            'ie_mutability': 'ie_mutability'
        }

        self._edge_storage_strategy = edge_storage_strategy
        self._sort_on_compaction = sort_on_compaction
        self._oe_mutability = oe_mutability
        self._ie_mutability = ie_mutability

    @classmethod
    def from_dict(cls, dikt) -> 'BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseEdgeType_vertex_type_pair_relations_inner_x_csr_params of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.  # noqa: E501
        :rtype: BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_storage_strategy(self) -> str:
        """Gets the edge_storage_strategy of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :return: The edge_storage_strategy of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :rtype: str
        """
        return self._edge_storage_strategy

    @edge_storage_strategy.setter
    def edge_storage_strategy(self, edge_storage_strategy: str):
        """Sets the edge_storage_strategy of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :param edge_storage_strategy: The edge_storage_strategy of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :type edge_storage_strategy: str
        """
        allowed_values = ["ONLY_IN", "ONLY_OUT", "BOTH_OUT_IN"]  # noqa: E501
        if edge_storage_strategy not in allowed_values:
            raise ValueError(
                "Invalid value for `edge_storage_strategy` ({0}), must be one of {1}"
                .format(edge_storage_strategy, allowed_values)
            )

        self._edge_storage_strategy = edge_storage_strategy

    @property
    def sort_on_compaction(self) -> bool:
        """Gets the sort_on_compaction of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :return: The sort_on_compaction of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :rtype: bool
        """
        return self._sort_on_compaction

    @sort_on_compaction.setter
    def sort_on_compaction(self, sort_on_compaction: bool):
        """Sets the sort_on_compaction of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :param sort_on_compaction: The sort_on_compaction of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :type sort_on_compaction: bool
        """

        self._sort_on_compaction = sort_on_compaction

    @property
    def oe_mutability(self) -> str:
        """Gets the oe_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :return: The oe_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :rtype: str
        """
        return self._oe_mutability

    @oe_mutability.setter
    def oe_mutability(self, oe_mutability: str):
        """Sets the oe_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :param oe_mutability: The oe_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :type oe_mutability: str
        """

        self._oe_mutability = oe_mutability

    @property
    def ie_mutability(self) -> str:
        """Gets the ie_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :return: The ie_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :rtype: str
        """
        return self._ie_mutability

    @ie_mutability.setter
    def ie_mutability(self, ie_mutability: str):
        """Sets the ie_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.


        :param ie_mutability: The ie_mutability of this BaseEdgeTypeVertexTypePairRelationsInnerXCsrParams.
        :type ie_mutability: str
        """

        self._ie_mutability = ie_mutability
