from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.edge_mapping_source_vertex_mappings_inner_column import EdgeMappingSourceVertexMappingsInnerColumn
from gs_interactive_admin import util

from gs_interactive_admin.models.edge_mapping_source_vertex_mappings_inner_column import EdgeMappingSourceVertexMappingsInnerColumn  # noqa: E501

class EdgeMappingDestinationVertexMappingsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, column=None, _property=None):  # noqa: E501
        """EdgeMappingDestinationVertexMappingsInner - a model defined in OpenAPI

        :param column: The column of this EdgeMappingDestinationVertexMappingsInner.  # noqa: E501
        :type column: EdgeMappingSourceVertexMappingsInnerColumn
        :param _property: The _property of this EdgeMappingDestinationVertexMappingsInner.  # noqa: E501
        :type _property: str
        """
        self.openapi_types = {
            'column': EdgeMappingSourceVertexMappingsInnerColumn,
            '_property': str
        }

        self.attribute_map = {
            'column': 'column',
            '_property': 'property'
        }

        self._column = column
        self.__property = _property

    @classmethod
    def from_dict(cls, dikt) -> 'EdgeMappingDestinationVertexMappingsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EdgeMapping_destination_vertex_mappings_inner of this EdgeMappingDestinationVertexMappingsInner.  # noqa: E501
        :rtype: EdgeMappingDestinationVertexMappingsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def column(self) -> EdgeMappingSourceVertexMappingsInnerColumn:
        """Gets the column of this EdgeMappingDestinationVertexMappingsInner.


        :return: The column of this EdgeMappingDestinationVertexMappingsInner.
        :rtype: EdgeMappingSourceVertexMappingsInnerColumn
        """
        return self._column

    @column.setter
    def column(self, column: EdgeMappingSourceVertexMappingsInnerColumn):
        """Sets the column of this EdgeMappingDestinationVertexMappingsInner.


        :param column: The column of this EdgeMappingDestinationVertexMappingsInner.
        :type column: EdgeMappingSourceVertexMappingsInnerColumn
        """

        self._column = column

    @property
    def _property(self) -> str:
        """Gets the _property of this EdgeMappingDestinationVertexMappingsInner.


        :return: The _property of this EdgeMappingDestinationVertexMappingsInner.
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property: str):
        """Sets the _property of this EdgeMappingDestinationVertexMappingsInner.


        :param _property: The _property of this EdgeMappingDestinationVertexMappingsInner.
        :type _property: str
        """

        self.__property = _property
