from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.parameter import Parameter
from gs_interactive_admin import util

from gs_interactive_admin.models.parameter import Parameter  # noqa: E501

class GetProcedureResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, type=None, query=None, id=None, library=None, params=None, returns=None, enable=None, option=None, bound_graph=None, runnable=None, creation_time=None, update_time=None):  # noqa: E501
        """GetProcedureResponse - a model defined in OpenAPI

        :param name: The name of this GetProcedureResponse.  # noqa: E501
        :type name: str
        :param description: The description of this GetProcedureResponse.  # noqa: E501
        :type description: str
        :param type: The type of this GetProcedureResponse.  # noqa: E501
        :type type: str
        :param query: The query of this GetProcedureResponse.  # noqa: E501
        :type query: str
        :param id: The id of this GetProcedureResponse.  # noqa: E501
        :type id: str
        :param library: The library of this GetProcedureResponse.  # noqa: E501
        :type library: str
        :param params: The params of this GetProcedureResponse.  # noqa: E501
        :type params: List[Parameter]
        :param returns: The returns of this GetProcedureResponse.  # noqa: E501
        :type returns: List[Parameter]
        :param enable: The enable of this GetProcedureResponse.  # noqa: E501
        :type enable: bool
        :param option: The option of this GetProcedureResponse.  # noqa: E501
        :type option: Dict[str, object]
        :param bound_graph: The bound_graph of this GetProcedureResponse.  # noqa: E501
        :type bound_graph: str
        :param runnable: The runnable of this GetProcedureResponse.  # noqa: E501
        :type runnable: bool
        :param creation_time: The creation_time of this GetProcedureResponse.  # noqa: E501
        :type creation_time: int
        :param update_time: The update_time of this GetProcedureResponse.  # noqa: E501
        :type update_time: int
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'type': str,
            'query': str,
            'id': str,
            'library': str,
            'params': List[Parameter],
            'returns': List[Parameter],
            'enable': bool,
            'option': Dict[str, object],
            'bound_graph': str,
            'runnable': bool,
            'creation_time': int,
            'update_time': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'type': 'type',
            'query': 'query',
            'id': 'id',
            'library': 'library',
            'params': 'params',
            'returns': 'returns',
            'enable': 'enable',
            'option': 'option',
            'bound_graph': 'bound_graph',
            'runnable': 'runnable',
            'creation_time': 'creation_time',
            'update_time': 'update_time'
        }

        self._name = name
        self._description = description
        self._type = type
        self._query = query
        self._id = id
        self._library = library
        self._params = params
        self._returns = returns
        self._enable = enable
        self._option = option
        self._bound_graph = bound_graph
        self._runnable = runnable
        self._creation_time = creation_time
        self._update_time = update_time

    @classmethod
    def from_dict(cls, dikt) -> 'GetProcedureResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProcedureResponse of this GetProcedureResponse.  # noqa: E501
        :rtype: GetProcedureResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GetProcedureResponse.


        :return: The name of this GetProcedureResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GetProcedureResponse.


        :param name: The name of this GetProcedureResponse.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this GetProcedureResponse.


        :return: The description of this GetProcedureResponse.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GetProcedureResponse.


        :param description: The description of this GetProcedureResponse.
        :type description: str
        """

        self._description = description

    @property
    def type(self) -> str:
        """Gets the type of this GetProcedureResponse.


        :return: The type of this GetProcedureResponse.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GetProcedureResponse.


        :param type: The type of this GetProcedureResponse.
        :type type: str
        """
        allowed_values = ["cpp", "cypher"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def query(self) -> str:
        """Gets the query of this GetProcedureResponse.


        :return: The query of this GetProcedureResponse.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query: str):
        """Sets the query of this GetProcedureResponse.


        :param query: The query of this GetProcedureResponse.
        :type query: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def id(self) -> str:
        """Gets the id of this GetProcedureResponse.


        :return: The id of this GetProcedureResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this GetProcedureResponse.


        :param id: The id of this GetProcedureResponse.
        :type id: str
        """

        self._id = id

    @property
    def library(self) -> str:
        """Gets the library of this GetProcedureResponse.


        :return: The library of this GetProcedureResponse.
        :rtype: str
        """
        return self._library

    @library.setter
    def library(self, library: str):
        """Sets the library of this GetProcedureResponse.


        :param library: The library of this GetProcedureResponse.
        :type library: str
        """

        self._library = library

    @property
    def params(self) -> List[Parameter]:
        """Gets the params of this GetProcedureResponse.


        :return: The params of this GetProcedureResponse.
        :rtype: List[Parameter]
        """
        return self._params

    @params.setter
    def params(self, params: List[Parameter]):
        """Sets the params of this GetProcedureResponse.


        :param params: The params of this GetProcedureResponse.
        :type params: List[Parameter]
        """

        self._params = params

    @property
    def returns(self) -> List[Parameter]:
        """Gets the returns of this GetProcedureResponse.


        :return: The returns of this GetProcedureResponse.
        :rtype: List[Parameter]
        """
        return self._returns

    @returns.setter
    def returns(self, returns: List[Parameter]):
        """Sets the returns of this GetProcedureResponse.


        :param returns: The returns of this GetProcedureResponse.
        :type returns: List[Parameter]
        """

        self._returns = returns

    @property
    def enable(self) -> bool:
        """Gets the enable of this GetProcedureResponse.


        :return: The enable of this GetProcedureResponse.
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable: bool):
        """Sets the enable of this GetProcedureResponse.


        :param enable: The enable of this GetProcedureResponse.
        :type enable: bool
        """

        self._enable = enable

    @property
    def option(self) -> Dict[str, object]:
        """Gets the option of this GetProcedureResponse.


        :return: The option of this GetProcedureResponse.
        :rtype: Dict[str, object]
        """
        return self._option

    @option.setter
    def option(self, option: Dict[str, object]):
        """Sets the option of this GetProcedureResponse.


        :param option: The option of this GetProcedureResponse.
        :type option: Dict[str, object]
        """

        self._option = option

    @property
    def bound_graph(self) -> str:
        """Gets the bound_graph of this GetProcedureResponse.


        :return: The bound_graph of this GetProcedureResponse.
        :rtype: str
        """
        return self._bound_graph

    @bound_graph.setter
    def bound_graph(self, bound_graph: str):
        """Sets the bound_graph of this GetProcedureResponse.


        :param bound_graph: The bound_graph of this GetProcedureResponse.
        :type bound_graph: str
        """

        self._bound_graph = bound_graph

    @property
    def runnable(self) -> bool:
        """Gets the runnable of this GetProcedureResponse.


        :return: The runnable of this GetProcedureResponse.
        :rtype: bool
        """
        return self._runnable

    @runnable.setter
    def runnable(self, runnable: bool):
        """Sets the runnable of this GetProcedureResponse.


        :param runnable: The runnable of this GetProcedureResponse.
        :type runnable: bool
        """

        self._runnable = runnable

    @property
    def creation_time(self) -> int:
        """Gets the creation_time of this GetProcedureResponse.


        :return: The creation_time of this GetProcedureResponse.
        :rtype: int
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time: int):
        """Sets the creation_time of this GetProcedureResponse.


        :param creation_time: The creation_time of this GetProcedureResponse.
        :type creation_time: int
        """

        self._creation_time = creation_time

    @property
    def update_time(self) -> int:
        """Gets the update_time of this GetProcedureResponse.


        :return: The update_time of this GetProcedureResponse.
        :rtype: int
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time: int):
        """Sets the update_time of this GetProcedureResponse.


        :param update_time: The update_time of this GetProcedureResponse.
        :type update_time: int
        """

        self._update_time = update_time
