from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.service_registry_record import ServiceRegistryRecord
from gs_interactive_admin import util

from gs_interactive_admin.models.service_registry_record import ServiceRegistryRecord  # noqa: E501

class GraphServiceRegistryRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, graph_id=None, service_registry=None):  # noqa: E501
        """GraphServiceRegistryRecord - a model defined in OpenAPI

        :param graph_id: The graph_id of this GraphServiceRegistryRecord.  # noqa: E501
        :type graph_id: str
        :param service_registry: The service_registry of this GraphServiceRegistryRecord.  # noqa: E501
        :type service_registry: ServiceRegistryRecord
        """
        self.openapi_types = {
            'graph_id': str,
            'service_registry': ServiceRegistryRecord
        }

        self.attribute_map = {
            'graph_id': 'graph_id',
            'service_registry': 'service_registry'
        }

        self._graph_id = graph_id
        self._service_registry = service_registry

    @classmethod
    def from_dict(cls, dikt) -> 'GraphServiceRegistryRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GraphServiceRegistryRecord of this GraphServiceRegistryRecord.  # noqa: E501
        :rtype: GraphServiceRegistryRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def graph_id(self) -> str:
        """Gets the graph_id of this GraphServiceRegistryRecord.


        :return: The graph_id of this GraphServiceRegistryRecord.
        :rtype: str
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id: str):
        """Sets the graph_id of this GraphServiceRegistryRecord.


        :param graph_id: The graph_id of this GraphServiceRegistryRecord.
        :type graph_id: str
        """

        self._graph_id = graph_id

    @property
    def service_registry(self) -> ServiceRegistryRecord:
        """Gets the service_registry of this GraphServiceRegistryRecord.


        :return: The service_registry of this GraphServiceRegistryRecord.
        :rtype: ServiceRegistryRecord
        """
        return self._service_registry

    @service_registry.setter
    def service_registry(self, service_registry: ServiceRegistryRecord):
        """Sets the service_registry of this GraphServiceRegistryRecord.


        :param service_registry: The service_registry of this GraphServiceRegistryRecord.
        :type service_registry: ServiceRegistryRecord
        """

        self._service_registry = service_registry
