from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.get_graph_response import GetGraphResponse
from gs_interactive_admin import util

from gs_interactive_admin.models.get_graph_response import GetGraphResponse  # noqa: E501

class ServiceStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deploy_mode=None, statistics_enabled=None, status=None, graph=None, bolt_port=None, hqps_port=None, gremlin_port=None, start_time=None):  # noqa: E501
        """ServiceStatus - a model defined in OpenAPI

        :param deploy_mode: The deploy_mode of this ServiceStatus.  # noqa: E501
        :type deploy_mode: str
        :param statistics_enabled: The statistics_enabled of this ServiceStatus.  # noqa: E501
        :type statistics_enabled: bool
        :param status: The status of this ServiceStatus.  # noqa: E501
        :type status: str
        :param graph: The graph of this ServiceStatus.  # noqa: E501
        :type graph: GetGraphResponse
        :param bolt_port: The bolt_port of this ServiceStatus.  # noqa: E501
        :type bolt_port: int
        :param hqps_port: The hqps_port of this ServiceStatus.  # noqa: E501
        :type hqps_port: int
        :param gremlin_port: The gremlin_port of this ServiceStatus.  # noqa: E501
        :type gremlin_port: int
        :param start_time: The start_time of this ServiceStatus.  # noqa: E501
        :type start_time: int
        """
        self.openapi_types = {
            'deploy_mode': str,
            'statistics_enabled': bool,
            'status': str,
            'graph': GetGraphResponse,
            'bolt_port': int,
            'hqps_port': int,
            'gremlin_port': int,
            'start_time': int
        }

        self.attribute_map = {
            'deploy_mode': 'deploy_mode',
            'statistics_enabled': 'statistics_enabled',
            'status': 'status',
            'graph': 'graph',
            'bolt_port': 'bolt_port',
            'hqps_port': 'hqps_port',
            'gremlin_port': 'gremlin_port',
            'start_time': 'start_time'
        }

        self._deploy_mode = deploy_mode
        self._statistics_enabled = statistics_enabled
        self._status = status
        self._graph = graph
        self._bolt_port = bolt_port
        self._hqps_port = hqps_port
        self._gremlin_port = gremlin_port
        self._start_time = start_time

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceStatus of this ServiceStatus.  # noqa: E501
        :rtype: ServiceStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deploy_mode(self) -> str:
        """Gets the deploy_mode of this ServiceStatus.


        :return: The deploy_mode of this ServiceStatus.
        :rtype: str
        """
        return self._deploy_mode

    @deploy_mode.setter
    def deploy_mode(self, deploy_mode: str):
        """Sets the deploy_mode of this ServiceStatus.


        :param deploy_mode: The deploy_mode of this ServiceStatus.
        :type deploy_mode: str
        """
        allowed_values = ["standalone", "k8s"]  # noqa: E501
        if deploy_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `deploy_mode` ({0}), must be one of {1}"
                .format(deploy_mode, allowed_values)
            )

        self._deploy_mode = deploy_mode

    @property
    def statistics_enabled(self) -> bool:
        """Gets the statistics_enabled of this ServiceStatus.


        :return: The statistics_enabled of this ServiceStatus.
        :rtype: bool
        """
        return self._statistics_enabled

    @statistics_enabled.setter
    def statistics_enabled(self, statistics_enabled: bool):
        """Sets the statistics_enabled of this ServiceStatus.


        :param statistics_enabled: The statistics_enabled of this ServiceStatus.
        :type statistics_enabled: bool
        """

        self._statistics_enabled = statistics_enabled

    @property
    def status(self) -> str:
        """Gets the status of this ServiceStatus.


        :return: The status of this ServiceStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ServiceStatus.


        :param status: The status of this ServiceStatus.
        :type status: str
        """

        self._status = status

    @property
    def graph(self) -> GetGraphResponse:
        """Gets the graph of this ServiceStatus.


        :return: The graph of this ServiceStatus.
        :rtype: GetGraphResponse
        """
        return self._graph

    @graph.setter
    def graph(self, graph: GetGraphResponse):
        """Sets the graph of this ServiceStatus.


        :param graph: The graph of this ServiceStatus.
        :type graph: GetGraphResponse
        """

        self._graph = graph

    @property
    def bolt_port(self) -> int:
        """Gets the bolt_port of this ServiceStatus.


        :return: The bolt_port of this ServiceStatus.
        :rtype: int
        """
        return self._bolt_port

    @bolt_port.setter
    def bolt_port(self, bolt_port: int):
        """Sets the bolt_port of this ServiceStatus.


        :param bolt_port: The bolt_port of this ServiceStatus.
        :type bolt_port: int
        """

        self._bolt_port = bolt_port

    @property
    def hqps_port(self) -> int:
        """Gets the hqps_port of this ServiceStatus.


        :return: The hqps_port of this ServiceStatus.
        :rtype: int
        """
        return self._hqps_port

    @hqps_port.setter
    def hqps_port(self, hqps_port: int):
        """Sets the hqps_port of this ServiceStatus.


        :param hqps_port: The hqps_port of this ServiceStatus.
        :type hqps_port: int
        """

        self._hqps_port = hqps_port

    @property
    def gremlin_port(self) -> int:
        """Gets the gremlin_port of this ServiceStatus.


        :return: The gremlin_port of this ServiceStatus.
        :rtype: int
        """
        return self._gremlin_port

    @gremlin_port.setter
    def gremlin_port(self, gremlin_port: int):
        """Sets the gremlin_port of this ServiceStatus.


        :param gremlin_port: The gremlin_port of this ServiceStatus.
        :type gremlin_port: int
        """

        self._gremlin_port = gremlin_port

    @property
    def start_time(self) -> int:
        """Gets the start_time of this ServiceStatus.


        :return: The start_time of this ServiceStatus.
        :rtype: int
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: int):
        """Sets the start_time of this ServiceStatus.


        :param start_time: The start_time of this ServiceStatus.
        :type start_time: int
        """

        self._start_time = start_time
