from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin import util


class ServiceMetrics(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, snapshot_id=None):  # noqa: E501
        """ServiceMetrics - a model defined in OpenAPI

        :param snapshot_id: The snapshot_id of this ServiceMetrics.  # noqa: E501
        :type snapshot_id: str
        """
        self.openapi_types = {
            'snapshot_id': str
        }

        self.attribute_map = {
            'snapshot_id': 'snapshot_id'
        }

        self._snapshot_id = snapshot_id

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceMetrics of this ServiceMetrics.  # noqa: E501
        :rtype: ServiceMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def snapshot_id(self) -> str:
        """Gets the snapshot_id of this ServiceMetrics.


        :return: The snapshot_id of this ServiceMetrics.
        :rtype: str
        """
        return self._snapshot_id

    @snapshot_id.setter
    def snapshot_id(self, snapshot_id: str):
        """Sets the snapshot_id of this ServiceMetrics.


        :param snapshot_id: The snapshot_id of this ServiceMetrics.
        :type snapshot_id: str
        """

        self._snapshot_id = snapshot_id
