from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.edge_request import EdgeRequest
from gs_interactive_admin.models.vertex_request import VertexRequest
from gs_interactive_admin import util

from gs_interactive_admin.models.edge_request import EdgeRequest  # noqa: E501
from gs_interactive_admin.models.vertex_request import VertexRequest  # noqa: E501

class VertexEdgeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vertex_request=None, edge_request=None):  # noqa: E501
        """VertexEdgeRequest - a model defined in OpenAPI

        :param vertex_request: The vertex_request of this VertexEdgeRequest.  # noqa: E501
        :type vertex_request: List[VertexRequest]
        :param edge_request: The edge_request of this VertexEdgeRequest.  # noqa: E501
        :type edge_request: List[EdgeRequest]
        """
        self.openapi_types = {
            'vertex_request': List[VertexRequest],
            'edge_request': List[EdgeRequest]
        }

        self.attribute_map = {
            'vertex_request': 'vertex_request',
            'edge_request': 'edge_request'
        }

        self._vertex_request = vertex_request
        self._edge_request = edge_request

    @classmethod
    def from_dict(cls, dikt) -> 'VertexEdgeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VertexEdgeRequest of this VertexEdgeRequest.  # noqa: E501
        :rtype: VertexEdgeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vertex_request(self) -> List[VertexRequest]:
        """Gets the vertex_request of this VertexEdgeRequest.


        :return: The vertex_request of this VertexEdgeRequest.
        :rtype: List[VertexRequest]
        """
        return self._vertex_request

    @vertex_request.setter
    def vertex_request(self, vertex_request: List[VertexRequest]):
        """Sets the vertex_request of this VertexEdgeRequest.


        :param vertex_request: The vertex_request of this VertexEdgeRequest.
        :type vertex_request: List[VertexRequest]
        """
        if vertex_request is None:
            raise ValueError("Invalid value for `vertex_request`, must not be `None`")  # noqa: E501

        self._vertex_request = vertex_request

    @property
    def edge_request(self) -> List[EdgeRequest]:
        """Gets the edge_request of this VertexEdgeRequest.


        :return: The edge_request of this VertexEdgeRequest.
        :rtype: List[EdgeRequest]
        """
        return self._edge_request

    @edge_request.setter
    def edge_request(self, edge_request: List[EdgeRequest]):
        """Sets the edge_request of this VertexEdgeRequest.


        :param edge_request: The edge_request of this VertexEdgeRequest.
        :type edge_request: List[EdgeRequest]
        """

        self._edge_request = edge_request
