// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_error_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_error_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_error_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_error_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_error_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace gs {
namespace neug {
namespace interactive {

enum Code : int {
  OK = 0,
  ERR_PERMISSION = 1001,
  ERR_VERSION_MISMATCHED = 1002,
  ERR_DIRECTORY_NOT_EXIST = 1003,
  ERR_DATABASE_LOCKED = 1004,
  ERR_DISK_SPACE_EXHAUSTED = 1005,
  ERR_CORRUPTION_DETECTED = 1006,
  ERR_INVALID_PATH = 1007,
  ERR_CONFIG_INVALID = 1008,
  ERR_INVALID_ARGUMENT = 1009,
  ERR_NOT_FOUND = 1010,
  ERR_NOT_SUPPORTED = 1011,
  ERR_INTERNAL_ERROR = 1012,
  ERR_ILLEGAL_OPERATION = 1013,
  ERR_IO_ERROR = 1014,
  ERR_BAD_ENCODING = 1015,
  ERR_INVALID_FILE = 1016,
  ERR_EXTENSION = 1017,
  ERR_NETWORK = 2001,
  ERR_SESSION_CLOSED = 2002,
  ERR_CONNECTION_CLOSED = 2003,
  ERR_POOL_EXHAUSTED = 2004,
  ERR_SERVICE_UNAVAILABLE = 2005,
  ERR_LOAD_OVERFLOW = 2006,
  ERR_CONNECTION_ERROR = 2007,
  ERR_COMPILATION = 3000,
  ERR_QUERY_EXECUTION = 3001,
  ERR_QUERY_SYNTAX = 3002,
  ERR_QUERY_TIMEOUT = 3003,
  ERR_CONCURRENT_WRITE = 3004,
  ERR_CODEGEN_ERROR = 3005,
  ERR_EMPTY_RESULT = 3006,
  ERR_NOT_INITIALIZED = 3007,
  ERR_TX_STATE_CONFLICT = 4001,
  ERR_WAL_WRITE_FAIL = 4002,
  ERR_TX_TIMEOUT = 4003,
  ERR_SCHEMA_MISMATCH = 5001,
  ERR_INVALID_SCHEMA = 5002,
  ERR_TYPE_CONVERSION = 5003,
  ERR_TYPE_OVERFLOW = 5004,
  ERR_INDEX_ERROR = 5005,
  ERR_PLATFORM_ABI = 6001,
  ERR_PY_BIND_INIT = 6002,
  ERR_ARCH_MISMATCH = 6003,
  ERR_DEPLOY_DEPENDENCY = 6004,
  ERR_NOT_IMPLEMENTED = 7001,
  ERR_UNKNOWN = 9999,
  Code_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Code_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Code_IsValid(int value);
constexpr Code Code_MIN = OK;
constexpr Code Code_MAX = ERR_UNKNOWN;
constexpr int Code_ARRAYSIZE = Code_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Code_descriptor();
template<typename T>
inline const std::string& Code_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Code>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Code_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Code_descriptor(), enum_t_value);
}
inline bool Code_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Code* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Code>(
    Code_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace interactive
}  // namespace neug
}  // namespace gs

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::gs::neug::interactive::Code> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gs::neug::interactive::Code>() {
  return ::gs::neug::interactive::Code_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_error_2eproto
