// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_type_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_type_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include "basic_type.pb.h"
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_type_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_type_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_type_2eproto;
namespace common {
class GraphDataType;
struct GraphDataTypeDefaultTypeInternal;
extern GraphDataTypeDefaultTypeInternal _GraphDataType_default_instance_;
class GraphDataType_GraphElementLabel;
struct GraphDataType_GraphElementLabelDefaultTypeInternal;
extern GraphDataType_GraphElementLabelDefaultTypeInternal _GraphDataType_GraphElementLabel_default_instance_;
class GraphDataType_GraphElementType;
struct GraphDataType_GraphElementTypeDefaultTypeInternal;
extern GraphDataType_GraphElementTypeDefaultTypeInternal _GraphDataType_GraphElementType_default_instance_;
class GraphDataType_GraphElementTypeField;
struct GraphDataType_GraphElementTypeFieldDefaultTypeInternal;
extern GraphDataType_GraphElementTypeFieldDefaultTypeInternal _GraphDataType_GraphElementTypeField_default_instance_;
class IrDataType;
struct IrDataTypeDefaultTypeInternal;
extern IrDataTypeDefaultTypeInternal _IrDataType_default_instance_;
}  // namespace common
PROTOBUF_NAMESPACE_OPEN
template<> ::common::GraphDataType* Arena::CreateMaybeMessage<::common::GraphDataType>(Arena*);
template<> ::common::GraphDataType_GraphElementLabel* Arena::CreateMaybeMessage<::common::GraphDataType_GraphElementLabel>(Arena*);
template<> ::common::GraphDataType_GraphElementType* Arena::CreateMaybeMessage<::common::GraphDataType_GraphElementType>(Arena*);
template<> ::common::GraphDataType_GraphElementTypeField* Arena::CreateMaybeMessage<::common::GraphDataType_GraphElementTypeField>(Arena*);
template<> ::common::IrDataType* Arena::CreateMaybeMessage<::common::IrDataType>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace common {

enum GraphDataType_GraphElementOpt : int {
  GraphDataType_GraphElementOpt_VERTEX = 0,
  GraphDataType_GraphElementOpt_EDGE = 1,
  GraphDataType_GraphElementOpt_PATH = 2,
  GraphDataType_GraphElementOpt_GraphDataType_GraphElementOpt_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GraphDataType_GraphElementOpt_GraphDataType_GraphElementOpt_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GraphDataType_GraphElementOpt_IsValid(int value);
constexpr GraphDataType_GraphElementOpt GraphDataType_GraphElementOpt_GraphElementOpt_MIN = GraphDataType_GraphElementOpt_VERTEX;
constexpr GraphDataType_GraphElementOpt GraphDataType_GraphElementOpt_GraphElementOpt_MAX = GraphDataType_GraphElementOpt_PATH;
constexpr int GraphDataType_GraphElementOpt_GraphElementOpt_ARRAYSIZE = GraphDataType_GraphElementOpt_GraphElementOpt_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GraphDataType_GraphElementOpt_descriptor();
template<typename T>
inline const std::string& GraphDataType_GraphElementOpt_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GraphDataType_GraphElementOpt>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GraphDataType_GraphElementOpt_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GraphDataType_GraphElementOpt_descriptor(), enum_t_value);
}
inline bool GraphDataType_GraphElementOpt_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GraphDataType_GraphElementOpt* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GraphDataType_GraphElementOpt>(
    GraphDataType_GraphElementOpt_descriptor(), name, value);
}
// ===================================================================

class GraphDataType_GraphElementLabel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:common.GraphDataType.GraphElementLabel) */ {
 public:
  inline GraphDataType_GraphElementLabel() : GraphDataType_GraphElementLabel(nullptr) {}
  ~GraphDataType_GraphElementLabel() override;
  explicit PROTOBUF_CONSTEXPR GraphDataType_GraphElementLabel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GraphDataType_GraphElementLabel(const GraphDataType_GraphElementLabel& from);
  GraphDataType_GraphElementLabel(GraphDataType_GraphElementLabel&& from) noexcept
    : GraphDataType_GraphElementLabel() {
    *this = ::std::move(from);
  }

  inline GraphDataType_GraphElementLabel& operator=(const GraphDataType_GraphElementLabel& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphDataType_GraphElementLabel& operator=(GraphDataType_GraphElementLabel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GraphDataType_GraphElementLabel& default_instance() {
    return *internal_default_instance();
  }
  static inline const GraphDataType_GraphElementLabel* internal_default_instance() {
    return reinterpret_cast<const GraphDataType_GraphElementLabel*>(
               &_GraphDataType_GraphElementLabel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GraphDataType_GraphElementLabel& a, GraphDataType_GraphElementLabel& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphDataType_GraphElementLabel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphDataType_GraphElementLabel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GraphDataType_GraphElementLabel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GraphDataType_GraphElementLabel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GraphDataType_GraphElementLabel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GraphDataType_GraphElementLabel& from) {
    GraphDataType_GraphElementLabel::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphDataType_GraphElementLabel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "common.GraphDataType.GraphElementLabel";
  }
  protected:
  explicit GraphDataType_GraphElementLabel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSrcLabelFieldNumber = 2,
    kDstLabelFieldNumber = 3,
    kLabelFieldNumber = 1,
  };
  // .google.protobuf.Int32Value src_label = 2;
  bool has_src_label() const;
  private:
  bool _internal_has_src_label() const;
  public:
  void clear_src_label();
  const ::PROTOBUF_NAMESPACE_ID::Int32Value& src_label() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Int32Value* release_src_label();
  ::PROTOBUF_NAMESPACE_ID::Int32Value* mutable_src_label();
  void set_allocated_src_label(::PROTOBUF_NAMESPACE_ID::Int32Value* src_label);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Int32Value& _internal_src_label() const;
  ::PROTOBUF_NAMESPACE_ID::Int32Value* _internal_mutable_src_label();
  public:
  void unsafe_arena_set_allocated_src_label(
      ::PROTOBUF_NAMESPACE_ID::Int32Value* src_label);
  ::PROTOBUF_NAMESPACE_ID::Int32Value* unsafe_arena_release_src_label();

  // .google.protobuf.Int32Value dst_label = 3;
  bool has_dst_label() const;
  private:
  bool _internal_has_dst_label() const;
  public:
  void clear_dst_label();
  const ::PROTOBUF_NAMESPACE_ID::Int32Value& dst_label() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Int32Value* release_dst_label();
  ::PROTOBUF_NAMESPACE_ID::Int32Value* mutable_dst_label();
  void set_allocated_dst_label(::PROTOBUF_NAMESPACE_ID::Int32Value* dst_label);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Int32Value& _internal_dst_label() const;
  ::PROTOBUF_NAMESPACE_ID::Int32Value* _internal_mutable_dst_label();
  public:
  void unsafe_arena_set_allocated_dst_label(
      ::PROTOBUF_NAMESPACE_ID::Int32Value* dst_label);
  ::PROTOBUF_NAMESPACE_ID::Int32Value* unsafe_arena_release_dst_label();

  // int32 label = 1;
  void clear_label();
  int32_t label() const;
  void set_label(int32_t value);
  private:
  int32_t _internal_label() const;
  void _internal_set_label(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementLabel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::Int32Value* src_label_;
    ::PROTOBUF_NAMESPACE_ID::Int32Value* dst_label_;
    int32_t label_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class GraphDataType_GraphElementTypeField final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:common.GraphDataType.GraphElementTypeField) */ {
 public:
  inline GraphDataType_GraphElementTypeField() : GraphDataType_GraphElementTypeField(nullptr) {}
  ~GraphDataType_GraphElementTypeField() override;
  explicit PROTOBUF_CONSTEXPR GraphDataType_GraphElementTypeField(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GraphDataType_GraphElementTypeField(const GraphDataType_GraphElementTypeField& from);
  GraphDataType_GraphElementTypeField(GraphDataType_GraphElementTypeField&& from) noexcept
    : GraphDataType_GraphElementTypeField() {
    *this = ::std::move(from);
  }

  inline GraphDataType_GraphElementTypeField& operator=(const GraphDataType_GraphElementTypeField& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphDataType_GraphElementTypeField& operator=(GraphDataType_GraphElementTypeField&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GraphDataType_GraphElementTypeField& default_instance() {
    return *internal_default_instance();
  }
  static inline const GraphDataType_GraphElementTypeField* internal_default_instance() {
    return reinterpret_cast<const GraphDataType_GraphElementTypeField*>(
               &_GraphDataType_GraphElementTypeField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GraphDataType_GraphElementTypeField& a, GraphDataType_GraphElementTypeField& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphDataType_GraphElementTypeField* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphDataType_GraphElementTypeField* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GraphDataType_GraphElementTypeField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GraphDataType_GraphElementTypeField>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GraphDataType_GraphElementTypeField& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GraphDataType_GraphElementTypeField& from) {
    GraphDataType_GraphElementTypeField::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphDataType_GraphElementTypeField* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "common.GraphDataType.GraphElementTypeField";
  }
  protected:
  explicit GraphDataType_GraphElementTypeField(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // .common.NameOrId prop_id = 1;
  bool has_prop_id() const;
  private:
  bool _internal_has_prop_id() const;
  public:
  void clear_prop_id();
  const ::common::NameOrId& prop_id() const;
  PROTOBUF_NODISCARD ::common::NameOrId* release_prop_id();
  ::common::NameOrId* mutable_prop_id();
  void set_allocated_prop_id(::common::NameOrId* prop_id);
  private:
  const ::common::NameOrId& _internal_prop_id() const;
  ::common::NameOrId* _internal_mutable_prop_id();
  public:
  void unsafe_arena_set_allocated_prop_id(
      ::common::NameOrId* prop_id);
  ::common::NameOrId* unsafe_arena_release_prop_id();

  // .common.DataType type = 2;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  const ::common::DataType& type() const;
  PROTOBUF_NODISCARD ::common::DataType* release_type();
  ::common::DataType* mutable_type();
  void set_allocated_type(::common::DataType* type);
  private:
  const ::common::DataType& _internal_type() const;
  ::common::DataType* _internal_mutable_type();
  public:
  void unsafe_arena_set_allocated_type(
      ::common::DataType* type);
  ::common::DataType* unsafe_arena_release_type();

  // @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementTypeField)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::common::NameOrId* prop_id_;
    ::common::DataType* type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class GraphDataType_GraphElementType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:common.GraphDataType.GraphElementType) */ {
 public:
  inline GraphDataType_GraphElementType() : GraphDataType_GraphElementType(nullptr) {}
  ~GraphDataType_GraphElementType() override;
  explicit PROTOBUF_CONSTEXPR GraphDataType_GraphElementType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GraphDataType_GraphElementType(const GraphDataType_GraphElementType& from);
  GraphDataType_GraphElementType(GraphDataType_GraphElementType&& from) noexcept
    : GraphDataType_GraphElementType() {
    *this = ::std::move(from);
  }

  inline GraphDataType_GraphElementType& operator=(const GraphDataType_GraphElementType& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphDataType_GraphElementType& operator=(GraphDataType_GraphElementType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GraphDataType_GraphElementType& default_instance() {
    return *internal_default_instance();
  }
  static inline const GraphDataType_GraphElementType* internal_default_instance() {
    return reinterpret_cast<const GraphDataType_GraphElementType*>(
               &_GraphDataType_GraphElementType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GraphDataType_GraphElementType& a, GraphDataType_GraphElementType& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphDataType_GraphElementType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphDataType_GraphElementType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GraphDataType_GraphElementType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GraphDataType_GraphElementType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GraphDataType_GraphElementType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GraphDataType_GraphElementType& from) {
    GraphDataType_GraphElementType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphDataType_GraphElementType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "common.GraphDataType.GraphElementType";
  }
  protected:
  explicit GraphDataType_GraphElementType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropsFieldNumber = 2,
    kLabelFieldNumber = 1,
  };
  // repeated .common.GraphDataType.GraphElementTypeField props = 2;
  int props_size() const;
  private:
  int _internal_props_size() const;
  public:
  void clear_props();
  ::common::GraphDataType_GraphElementTypeField* mutable_props(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementTypeField >*
      mutable_props();
  private:
  const ::common::GraphDataType_GraphElementTypeField& _internal_props(int index) const;
  ::common::GraphDataType_GraphElementTypeField* _internal_add_props();
  public:
  const ::common::GraphDataType_GraphElementTypeField& props(int index) const;
  ::common::GraphDataType_GraphElementTypeField* add_props();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementTypeField >&
      props() const;

  // .common.GraphDataType.GraphElementLabel label = 1;
  bool has_label() const;
  private:
  bool _internal_has_label() const;
  public:
  void clear_label();
  const ::common::GraphDataType_GraphElementLabel& label() const;
  PROTOBUF_NODISCARD ::common::GraphDataType_GraphElementLabel* release_label();
  ::common::GraphDataType_GraphElementLabel* mutable_label();
  void set_allocated_label(::common::GraphDataType_GraphElementLabel* label);
  private:
  const ::common::GraphDataType_GraphElementLabel& _internal_label() const;
  ::common::GraphDataType_GraphElementLabel* _internal_mutable_label();
  public:
  void unsafe_arena_set_allocated_label(
      ::common::GraphDataType_GraphElementLabel* label);
  ::common::GraphDataType_GraphElementLabel* unsafe_arena_release_label();

  // @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementType)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementTypeField > props_;
    ::common::GraphDataType_GraphElementLabel* label_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class GraphDataType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:common.GraphDataType) */ {
 public:
  inline GraphDataType() : GraphDataType(nullptr) {}
  ~GraphDataType() override;
  explicit PROTOBUF_CONSTEXPR GraphDataType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GraphDataType(const GraphDataType& from);
  GraphDataType(GraphDataType&& from) noexcept
    : GraphDataType() {
    *this = ::std::move(from);
  }

  inline GraphDataType& operator=(const GraphDataType& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphDataType& operator=(GraphDataType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GraphDataType& default_instance() {
    return *internal_default_instance();
  }
  static inline const GraphDataType* internal_default_instance() {
    return reinterpret_cast<const GraphDataType*>(
               &_GraphDataType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GraphDataType& a, GraphDataType& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphDataType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphDataType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GraphDataType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GraphDataType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GraphDataType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GraphDataType& from) {
    GraphDataType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphDataType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "common.GraphDataType";
  }
  protected:
  explicit GraphDataType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GraphDataType_GraphElementLabel GraphElementLabel;
  typedef GraphDataType_GraphElementTypeField GraphElementTypeField;
  typedef GraphDataType_GraphElementType GraphElementType;

  typedef GraphDataType_GraphElementOpt GraphElementOpt;
  static constexpr GraphElementOpt VERTEX =
    GraphDataType_GraphElementOpt_VERTEX;
  static constexpr GraphElementOpt EDGE =
    GraphDataType_GraphElementOpt_EDGE;
  static constexpr GraphElementOpt PATH =
    GraphDataType_GraphElementOpt_PATH;
  static inline bool GraphElementOpt_IsValid(int value) {
    return GraphDataType_GraphElementOpt_IsValid(value);
  }
  static constexpr GraphElementOpt GraphElementOpt_MIN =
    GraphDataType_GraphElementOpt_GraphElementOpt_MIN;
  static constexpr GraphElementOpt GraphElementOpt_MAX =
    GraphDataType_GraphElementOpt_GraphElementOpt_MAX;
  static constexpr int GraphElementOpt_ARRAYSIZE =
    GraphDataType_GraphElementOpt_GraphElementOpt_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  GraphElementOpt_descriptor() {
    return GraphDataType_GraphElementOpt_descriptor();
  }
  template<typename T>
  static inline const std::string& GraphElementOpt_Name(T enum_t_value) {
    static_assert(::std::is_same<T, GraphElementOpt>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function GraphElementOpt_Name.");
    return GraphDataType_GraphElementOpt_Name(enum_t_value);
  }
  static inline bool GraphElementOpt_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      GraphElementOpt* value) {
    return GraphDataType_GraphElementOpt_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kGraphDataTypeFieldNumber = 2,
    kElementOptFieldNumber = 1,
  };
  // repeated .common.GraphDataType.GraphElementType graph_data_type = 2;
  int graph_data_type_size() const;
  private:
  int _internal_graph_data_type_size() const;
  public:
  void clear_graph_data_type();
  ::common::GraphDataType_GraphElementType* mutable_graph_data_type(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementType >*
      mutable_graph_data_type();
  private:
  const ::common::GraphDataType_GraphElementType& _internal_graph_data_type(int index) const;
  ::common::GraphDataType_GraphElementType* _internal_add_graph_data_type();
  public:
  const ::common::GraphDataType_GraphElementType& graph_data_type(int index) const;
  ::common::GraphDataType_GraphElementType* add_graph_data_type();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementType >&
      graph_data_type() const;

  // .common.GraphDataType.GraphElementOpt element_opt = 1;
  void clear_element_opt();
  ::common::GraphDataType_GraphElementOpt element_opt() const;
  void set_element_opt(::common::GraphDataType_GraphElementOpt value);
  private:
  ::common::GraphDataType_GraphElementOpt _internal_element_opt() const;
  void _internal_set_element_opt(::common::GraphDataType_GraphElementOpt value);
  public:

  // @@protoc_insertion_point(class_scope:common.GraphDataType)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementType > graph_data_type_;
    int element_opt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_type_2eproto;
};
// -------------------------------------------------------------------

class IrDataType final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:common.IrDataType) */ {
 public:
  inline IrDataType() : IrDataType(nullptr) {}
  ~IrDataType() override;
  explicit PROTOBUF_CONSTEXPR IrDataType(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IrDataType(const IrDataType& from);
  IrDataType(IrDataType&& from) noexcept
    : IrDataType() {
    *this = ::std::move(from);
  }

  inline IrDataType& operator=(const IrDataType& from) {
    CopyFrom(from);
    return *this;
  }
  inline IrDataType& operator=(IrDataType&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IrDataType& default_instance() {
    return *internal_default_instance();
  }
  enum TypeCase {
    kDataType = 1,
    kGraphType = 2,
    TYPE_NOT_SET = 0,
  };

  static inline const IrDataType* internal_default_instance() {
    return reinterpret_cast<const IrDataType*>(
               &_IrDataType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(IrDataType& a, IrDataType& b) {
    a.Swap(&b);
  }
  inline void Swap(IrDataType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IrDataType* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IrDataType* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IrDataType>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IrDataType& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IrDataType& from) {
    IrDataType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IrDataType* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "common.IrDataType";
  }
  protected:
  explicit IrDataType(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataTypeFieldNumber = 1,
    kGraphTypeFieldNumber = 2,
  };
  // .common.DataType data_type = 1;
  bool has_data_type() const;
  private:
  bool _internal_has_data_type() const;
  public:
  void clear_data_type();
  const ::common::DataType& data_type() const;
  PROTOBUF_NODISCARD ::common::DataType* release_data_type();
  ::common::DataType* mutable_data_type();
  void set_allocated_data_type(::common::DataType* data_type);
  private:
  const ::common::DataType& _internal_data_type() const;
  ::common::DataType* _internal_mutable_data_type();
  public:
  void unsafe_arena_set_allocated_data_type(
      ::common::DataType* data_type);
  ::common::DataType* unsafe_arena_release_data_type();

  // .common.GraphDataType graph_type = 2;
  bool has_graph_type() const;
  private:
  bool _internal_has_graph_type() const;
  public:
  void clear_graph_type();
  const ::common::GraphDataType& graph_type() const;
  PROTOBUF_NODISCARD ::common::GraphDataType* release_graph_type();
  ::common::GraphDataType* mutable_graph_type();
  void set_allocated_graph_type(::common::GraphDataType* graph_type);
  private:
  const ::common::GraphDataType& _internal_graph_type() const;
  ::common::GraphDataType* _internal_mutable_graph_type();
  public:
  void unsafe_arena_set_allocated_graph_type(
      ::common::GraphDataType* graph_type);
  ::common::GraphDataType* unsafe_arena_release_graph_type();

  void clear_type();
  TypeCase type_case() const;
  // @@protoc_insertion_point(class_scope:common.IrDataType)
 private:
  class _Internal;
  void set_has_data_type();
  void set_has_graph_type();

  inline bool has_type() const;
  inline void clear_has_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union TypeUnion {
      constexpr TypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::common::DataType* data_type_;
      ::common::GraphDataType* graph_type_;
    } type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_type_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphDataType_GraphElementLabel

// int32 label = 1;
inline void GraphDataType_GraphElementLabel::clear_label() {
  _impl_.label_ = 0;
}
inline int32_t GraphDataType_GraphElementLabel::_internal_label() const {
  return _impl_.label_;
}
inline int32_t GraphDataType_GraphElementLabel::label() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementLabel.label)
  return _internal_label();
}
inline void GraphDataType_GraphElementLabel::_internal_set_label(int32_t value) {
  
  _impl_.label_ = value;
}
inline void GraphDataType_GraphElementLabel::set_label(int32_t value) {
  _internal_set_label(value);
  // @@protoc_insertion_point(field_set:common.GraphDataType.GraphElementLabel.label)
}

// .google.protobuf.Int32Value src_label = 2;
inline bool GraphDataType_GraphElementLabel::_internal_has_src_label() const {
  return this != internal_default_instance() && _impl_.src_label_ != nullptr;
}
inline bool GraphDataType_GraphElementLabel::has_src_label() const {
  return _internal_has_src_label();
}
inline const ::PROTOBUF_NAMESPACE_ID::Int32Value& GraphDataType_GraphElementLabel::_internal_src_label() const {
  const ::PROTOBUF_NAMESPACE_ID::Int32Value* p = _impl_.src_label_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Int32Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Int32Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Int32Value& GraphDataType_GraphElementLabel::src_label() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementLabel.src_label)
  return _internal_src_label();
}
inline void GraphDataType_GraphElementLabel::unsafe_arena_set_allocated_src_label(
    ::PROTOBUF_NAMESPACE_ID::Int32Value* src_label) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.src_label_);
  }
  _impl_.src_label_ = src_label;
  if (src_label) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.GraphDataType.GraphElementLabel.src_label)
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::release_src_label() {
  
  ::PROTOBUF_NAMESPACE_ID::Int32Value* temp = _impl_.src_label_;
  _impl_.src_label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::unsafe_arena_release_src_label() {
  // @@protoc_insertion_point(field_release:common.GraphDataType.GraphElementLabel.src_label)
  
  ::PROTOBUF_NAMESPACE_ID::Int32Value* temp = _impl_.src_label_;
  _impl_.src_label_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::_internal_mutable_src_label() {
  
  if (_impl_.src_label_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Int32Value>(GetArenaForAllocation());
    _impl_.src_label_ = p;
  }
  return _impl_.src_label_;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::mutable_src_label() {
  ::PROTOBUF_NAMESPACE_ID::Int32Value* _msg = _internal_mutable_src_label();
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementLabel.src_label)
  return _msg;
}
inline void GraphDataType_GraphElementLabel::set_allocated_src_label(::PROTOBUF_NAMESPACE_ID::Int32Value* src_label) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.src_label_);
  }
  if (src_label) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(src_label));
    if (message_arena != submessage_arena) {
      src_label = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, src_label, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.src_label_ = src_label;
  // @@protoc_insertion_point(field_set_allocated:common.GraphDataType.GraphElementLabel.src_label)
}

// .google.protobuf.Int32Value dst_label = 3;
inline bool GraphDataType_GraphElementLabel::_internal_has_dst_label() const {
  return this != internal_default_instance() && _impl_.dst_label_ != nullptr;
}
inline bool GraphDataType_GraphElementLabel::has_dst_label() const {
  return _internal_has_dst_label();
}
inline const ::PROTOBUF_NAMESPACE_ID::Int32Value& GraphDataType_GraphElementLabel::_internal_dst_label() const {
  const ::PROTOBUF_NAMESPACE_ID::Int32Value* p = _impl_.dst_label_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Int32Value&>(
      ::PROTOBUF_NAMESPACE_ID::_Int32Value_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Int32Value& GraphDataType_GraphElementLabel::dst_label() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementLabel.dst_label)
  return _internal_dst_label();
}
inline void GraphDataType_GraphElementLabel::unsafe_arena_set_allocated_dst_label(
    ::PROTOBUF_NAMESPACE_ID::Int32Value* dst_label) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.dst_label_);
  }
  _impl_.dst_label_ = dst_label;
  if (dst_label) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.GraphDataType.GraphElementLabel.dst_label)
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::release_dst_label() {
  
  ::PROTOBUF_NAMESPACE_ID::Int32Value* temp = _impl_.dst_label_;
  _impl_.dst_label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::unsafe_arena_release_dst_label() {
  // @@protoc_insertion_point(field_release:common.GraphDataType.GraphElementLabel.dst_label)
  
  ::PROTOBUF_NAMESPACE_ID::Int32Value* temp = _impl_.dst_label_;
  _impl_.dst_label_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::_internal_mutable_dst_label() {
  
  if (_impl_.dst_label_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Int32Value>(GetArenaForAllocation());
    _impl_.dst_label_ = p;
  }
  return _impl_.dst_label_;
}
inline ::PROTOBUF_NAMESPACE_ID::Int32Value* GraphDataType_GraphElementLabel::mutable_dst_label() {
  ::PROTOBUF_NAMESPACE_ID::Int32Value* _msg = _internal_mutable_dst_label();
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementLabel.dst_label)
  return _msg;
}
inline void GraphDataType_GraphElementLabel::set_allocated_dst_label(::PROTOBUF_NAMESPACE_ID::Int32Value* dst_label) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.dst_label_);
  }
  if (dst_label) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(dst_label));
    if (message_arena != submessage_arena) {
      dst_label = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dst_label, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.dst_label_ = dst_label;
  // @@protoc_insertion_point(field_set_allocated:common.GraphDataType.GraphElementLabel.dst_label)
}

// -------------------------------------------------------------------

// GraphDataType_GraphElementTypeField

// .common.NameOrId prop_id = 1;
inline bool GraphDataType_GraphElementTypeField::_internal_has_prop_id() const {
  return this != internal_default_instance() && _impl_.prop_id_ != nullptr;
}
inline bool GraphDataType_GraphElementTypeField::has_prop_id() const {
  return _internal_has_prop_id();
}
inline const ::common::NameOrId& GraphDataType_GraphElementTypeField::_internal_prop_id() const {
  const ::common::NameOrId* p = _impl_.prop_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::NameOrId&>(
      ::common::_NameOrId_default_instance_);
}
inline const ::common::NameOrId& GraphDataType_GraphElementTypeField::prop_id() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementTypeField.prop_id)
  return _internal_prop_id();
}
inline void GraphDataType_GraphElementTypeField::unsafe_arena_set_allocated_prop_id(
    ::common::NameOrId* prop_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.prop_id_);
  }
  _impl_.prop_id_ = prop_id;
  if (prop_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.GraphDataType.GraphElementTypeField.prop_id)
}
inline ::common::NameOrId* GraphDataType_GraphElementTypeField::release_prop_id() {
  
  ::common::NameOrId* temp = _impl_.prop_id_;
  _impl_.prop_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::NameOrId* GraphDataType_GraphElementTypeField::unsafe_arena_release_prop_id() {
  // @@protoc_insertion_point(field_release:common.GraphDataType.GraphElementTypeField.prop_id)
  
  ::common::NameOrId* temp = _impl_.prop_id_;
  _impl_.prop_id_ = nullptr;
  return temp;
}
inline ::common::NameOrId* GraphDataType_GraphElementTypeField::_internal_mutable_prop_id() {
  
  if (_impl_.prop_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::NameOrId>(GetArenaForAllocation());
    _impl_.prop_id_ = p;
  }
  return _impl_.prop_id_;
}
inline ::common::NameOrId* GraphDataType_GraphElementTypeField::mutable_prop_id() {
  ::common::NameOrId* _msg = _internal_mutable_prop_id();
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementTypeField.prop_id)
  return _msg;
}
inline void GraphDataType_GraphElementTypeField::set_allocated_prop_id(::common::NameOrId* prop_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.prop_id_);
  }
  if (prop_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(prop_id));
    if (message_arena != submessage_arena) {
      prop_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, prop_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.prop_id_ = prop_id;
  // @@protoc_insertion_point(field_set_allocated:common.GraphDataType.GraphElementTypeField.prop_id)
}

// .common.DataType type = 2;
inline bool GraphDataType_GraphElementTypeField::_internal_has_type() const {
  return this != internal_default_instance() && _impl_.type_ != nullptr;
}
inline bool GraphDataType_GraphElementTypeField::has_type() const {
  return _internal_has_type();
}
inline const ::common::DataType& GraphDataType_GraphElementTypeField::_internal_type() const {
  const ::common::DataType* p = _impl_.type_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::DataType&>(
      ::common::_DataType_default_instance_);
}
inline const ::common::DataType& GraphDataType_GraphElementTypeField::type() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementTypeField.type)
  return _internal_type();
}
inline void GraphDataType_GraphElementTypeField::unsafe_arena_set_allocated_type(
    ::common::DataType* type) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.type_);
  }
  _impl_.type_ = type;
  if (type) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.GraphDataType.GraphElementTypeField.type)
}
inline ::common::DataType* GraphDataType_GraphElementTypeField::release_type() {
  
  ::common::DataType* temp = _impl_.type_;
  _impl_.type_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::DataType* GraphDataType_GraphElementTypeField::unsafe_arena_release_type() {
  // @@protoc_insertion_point(field_release:common.GraphDataType.GraphElementTypeField.type)
  
  ::common::DataType* temp = _impl_.type_;
  _impl_.type_ = nullptr;
  return temp;
}
inline ::common::DataType* GraphDataType_GraphElementTypeField::_internal_mutable_type() {
  
  if (_impl_.type_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::DataType>(GetArenaForAllocation());
    _impl_.type_ = p;
  }
  return _impl_.type_;
}
inline ::common::DataType* GraphDataType_GraphElementTypeField::mutable_type() {
  ::common::DataType* _msg = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementTypeField.type)
  return _msg;
}
inline void GraphDataType_GraphElementTypeField::set_allocated_type(::common::DataType* type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.type_);
  }
  if (type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(type));
    if (message_arena != submessage_arena) {
      type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, type, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.type_ = type;
  // @@protoc_insertion_point(field_set_allocated:common.GraphDataType.GraphElementTypeField.type)
}

// -------------------------------------------------------------------

// GraphDataType_GraphElementType

// .common.GraphDataType.GraphElementLabel label = 1;
inline bool GraphDataType_GraphElementType::_internal_has_label() const {
  return this != internal_default_instance() && _impl_.label_ != nullptr;
}
inline bool GraphDataType_GraphElementType::has_label() const {
  return _internal_has_label();
}
inline void GraphDataType_GraphElementType::clear_label() {
  if (GetArenaForAllocation() == nullptr && _impl_.label_ != nullptr) {
    delete _impl_.label_;
  }
  _impl_.label_ = nullptr;
}
inline const ::common::GraphDataType_GraphElementLabel& GraphDataType_GraphElementType::_internal_label() const {
  const ::common::GraphDataType_GraphElementLabel* p = _impl_.label_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::GraphDataType_GraphElementLabel&>(
      ::common::_GraphDataType_GraphElementLabel_default_instance_);
}
inline const ::common::GraphDataType_GraphElementLabel& GraphDataType_GraphElementType::label() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementType.label)
  return _internal_label();
}
inline void GraphDataType_GraphElementType::unsafe_arena_set_allocated_label(
    ::common::GraphDataType_GraphElementLabel* label) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.label_);
  }
  _impl_.label_ = label;
  if (label) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.GraphDataType.GraphElementType.label)
}
inline ::common::GraphDataType_GraphElementLabel* GraphDataType_GraphElementType::release_label() {
  
  ::common::GraphDataType_GraphElementLabel* temp = _impl_.label_;
  _impl_.label_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::GraphDataType_GraphElementLabel* GraphDataType_GraphElementType::unsafe_arena_release_label() {
  // @@protoc_insertion_point(field_release:common.GraphDataType.GraphElementType.label)
  
  ::common::GraphDataType_GraphElementLabel* temp = _impl_.label_;
  _impl_.label_ = nullptr;
  return temp;
}
inline ::common::GraphDataType_GraphElementLabel* GraphDataType_GraphElementType::_internal_mutable_label() {
  
  if (_impl_.label_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::GraphDataType_GraphElementLabel>(GetArenaForAllocation());
    _impl_.label_ = p;
  }
  return _impl_.label_;
}
inline ::common::GraphDataType_GraphElementLabel* GraphDataType_GraphElementType::mutable_label() {
  ::common::GraphDataType_GraphElementLabel* _msg = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementType.label)
  return _msg;
}
inline void GraphDataType_GraphElementType::set_allocated_label(::common::GraphDataType_GraphElementLabel* label) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.label_;
  }
  if (label) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(label);
    if (message_arena != submessage_arena) {
      label = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, label, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.label_ = label;
  // @@protoc_insertion_point(field_set_allocated:common.GraphDataType.GraphElementType.label)
}

// repeated .common.GraphDataType.GraphElementTypeField props = 2;
inline int GraphDataType_GraphElementType::_internal_props_size() const {
  return _impl_.props_.size();
}
inline int GraphDataType_GraphElementType::props_size() const {
  return _internal_props_size();
}
inline void GraphDataType_GraphElementType::clear_props() {
  _impl_.props_.Clear();
}
inline ::common::GraphDataType_GraphElementTypeField* GraphDataType_GraphElementType::mutable_props(int index) {
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.GraphElementType.props)
  return _impl_.props_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementTypeField >*
GraphDataType_GraphElementType::mutable_props() {
  // @@protoc_insertion_point(field_mutable_list:common.GraphDataType.GraphElementType.props)
  return &_impl_.props_;
}
inline const ::common::GraphDataType_GraphElementTypeField& GraphDataType_GraphElementType::_internal_props(int index) const {
  return _impl_.props_.Get(index);
}
inline const ::common::GraphDataType_GraphElementTypeField& GraphDataType_GraphElementType::props(int index) const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.GraphElementType.props)
  return _internal_props(index);
}
inline ::common::GraphDataType_GraphElementTypeField* GraphDataType_GraphElementType::_internal_add_props() {
  return _impl_.props_.Add();
}
inline ::common::GraphDataType_GraphElementTypeField* GraphDataType_GraphElementType::add_props() {
  ::common::GraphDataType_GraphElementTypeField* _add = _internal_add_props();
  // @@protoc_insertion_point(field_add:common.GraphDataType.GraphElementType.props)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementTypeField >&
GraphDataType_GraphElementType::props() const {
  // @@protoc_insertion_point(field_list:common.GraphDataType.GraphElementType.props)
  return _impl_.props_;
}

// -------------------------------------------------------------------

// GraphDataType

// .common.GraphDataType.GraphElementOpt element_opt = 1;
inline void GraphDataType::clear_element_opt() {
  _impl_.element_opt_ = 0;
}
inline ::common::GraphDataType_GraphElementOpt GraphDataType::_internal_element_opt() const {
  return static_cast< ::common::GraphDataType_GraphElementOpt >(_impl_.element_opt_);
}
inline ::common::GraphDataType_GraphElementOpt GraphDataType::element_opt() const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.element_opt)
  return _internal_element_opt();
}
inline void GraphDataType::_internal_set_element_opt(::common::GraphDataType_GraphElementOpt value) {
  
  _impl_.element_opt_ = value;
}
inline void GraphDataType::set_element_opt(::common::GraphDataType_GraphElementOpt value) {
  _internal_set_element_opt(value);
  // @@protoc_insertion_point(field_set:common.GraphDataType.element_opt)
}

// repeated .common.GraphDataType.GraphElementType graph_data_type = 2;
inline int GraphDataType::_internal_graph_data_type_size() const {
  return _impl_.graph_data_type_.size();
}
inline int GraphDataType::graph_data_type_size() const {
  return _internal_graph_data_type_size();
}
inline void GraphDataType::clear_graph_data_type() {
  _impl_.graph_data_type_.Clear();
}
inline ::common::GraphDataType_GraphElementType* GraphDataType::mutable_graph_data_type(int index) {
  // @@protoc_insertion_point(field_mutable:common.GraphDataType.graph_data_type)
  return _impl_.graph_data_type_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementType >*
GraphDataType::mutable_graph_data_type() {
  // @@protoc_insertion_point(field_mutable_list:common.GraphDataType.graph_data_type)
  return &_impl_.graph_data_type_;
}
inline const ::common::GraphDataType_GraphElementType& GraphDataType::_internal_graph_data_type(int index) const {
  return _impl_.graph_data_type_.Get(index);
}
inline const ::common::GraphDataType_GraphElementType& GraphDataType::graph_data_type(int index) const {
  // @@protoc_insertion_point(field_get:common.GraphDataType.graph_data_type)
  return _internal_graph_data_type(index);
}
inline ::common::GraphDataType_GraphElementType* GraphDataType::_internal_add_graph_data_type() {
  return _impl_.graph_data_type_.Add();
}
inline ::common::GraphDataType_GraphElementType* GraphDataType::add_graph_data_type() {
  ::common::GraphDataType_GraphElementType* _add = _internal_add_graph_data_type();
  // @@protoc_insertion_point(field_add:common.GraphDataType.graph_data_type)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::GraphDataType_GraphElementType >&
GraphDataType::graph_data_type() const {
  // @@protoc_insertion_point(field_list:common.GraphDataType.graph_data_type)
  return _impl_.graph_data_type_;
}

// -------------------------------------------------------------------

// IrDataType

// .common.DataType data_type = 1;
inline bool IrDataType::_internal_has_data_type() const {
  return type_case() == kDataType;
}
inline bool IrDataType::has_data_type() const {
  return _internal_has_data_type();
}
inline void IrDataType::set_has_data_type() {
  _impl_._oneof_case_[0] = kDataType;
}
inline ::common::DataType* IrDataType::release_data_type() {
  // @@protoc_insertion_point(field_release:common.IrDataType.data_type)
  if (_internal_has_data_type()) {
    clear_has_type();
    ::common::DataType* temp = _impl_.type_.data_type_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.type_.data_type_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::common::DataType& IrDataType::_internal_data_type() const {
  return _internal_has_data_type()
      ? *_impl_.type_.data_type_
      : reinterpret_cast< ::common::DataType&>(::common::_DataType_default_instance_);
}
inline const ::common::DataType& IrDataType::data_type() const {
  // @@protoc_insertion_point(field_get:common.IrDataType.data_type)
  return _internal_data_type();
}
inline ::common::DataType* IrDataType::unsafe_arena_release_data_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:common.IrDataType.data_type)
  if (_internal_has_data_type()) {
    clear_has_type();
    ::common::DataType* temp = _impl_.type_.data_type_;
    _impl_.type_.data_type_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IrDataType::unsafe_arena_set_allocated_data_type(::common::DataType* data_type) {
  clear_type();
  if (data_type) {
    set_has_data_type();
    _impl_.type_.data_type_ = data_type;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.IrDataType.data_type)
}
inline ::common::DataType* IrDataType::_internal_mutable_data_type() {
  if (!_internal_has_data_type()) {
    clear_type();
    set_has_data_type();
    _impl_.type_.data_type_ = CreateMaybeMessage< ::common::DataType >(GetArenaForAllocation());
  }
  return _impl_.type_.data_type_;
}
inline ::common::DataType* IrDataType::mutable_data_type() {
  ::common::DataType* _msg = _internal_mutable_data_type();
  // @@protoc_insertion_point(field_mutable:common.IrDataType.data_type)
  return _msg;
}

// .common.GraphDataType graph_type = 2;
inline bool IrDataType::_internal_has_graph_type() const {
  return type_case() == kGraphType;
}
inline bool IrDataType::has_graph_type() const {
  return _internal_has_graph_type();
}
inline void IrDataType::set_has_graph_type() {
  _impl_._oneof_case_[0] = kGraphType;
}
inline void IrDataType::clear_graph_type() {
  if (_internal_has_graph_type()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.type_.graph_type_;
    }
    clear_has_type();
  }
}
inline ::common::GraphDataType* IrDataType::release_graph_type() {
  // @@protoc_insertion_point(field_release:common.IrDataType.graph_type)
  if (_internal_has_graph_type()) {
    clear_has_type();
    ::common::GraphDataType* temp = _impl_.type_.graph_type_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.type_.graph_type_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::common::GraphDataType& IrDataType::_internal_graph_type() const {
  return _internal_has_graph_type()
      ? *_impl_.type_.graph_type_
      : reinterpret_cast< ::common::GraphDataType&>(::common::_GraphDataType_default_instance_);
}
inline const ::common::GraphDataType& IrDataType::graph_type() const {
  // @@protoc_insertion_point(field_get:common.IrDataType.graph_type)
  return _internal_graph_type();
}
inline ::common::GraphDataType* IrDataType::unsafe_arena_release_graph_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:common.IrDataType.graph_type)
  if (_internal_has_graph_type()) {
    clear_has_type();
    ::common::GraphDataType* temp = _impl_.type_.graph_type_;
    _impl_.type_.graph_type_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IrDataType::unsafe_arena_set_allocated_graph_type(::common::GraphDataType* graph_type) {
  clear_type();
  if (graph_type) {
    set_has_graph_type();
    _impl_.type_.graph_type_ = graph_type;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:common.IrDataType.graph_type)
}
inline ::common::GraphDataType* IrDataType::_internal_mutable_graph_type() {
  if (!_internal_has_graph_type()) {
    clear_type();
    set_has_graph_type();
    _impl_.type_.graph_type_ = CreateMaybeMessage< ::common::GraphDataType >(GetArenaForAllocation());
  }
  return _impl_.type_.graph_type_;
}
inline ::common::GraphDataType* IrDataType::mutable_graph_type() {
  ::common::GraphDataType* _msg = _internal_mutable_graph_type();
  // @@protoc_insertion_point(field_mutable:common.IrDataType.graph_type)
  return _msg;
}

inline bool IrDataType::has_type() const {
  return type_case() != TYPE_NOT_SET;
}
inline void IrDataType::clear_has_type() {
  _impl_._oneof_case_[0] = TYPE_NOT_SET;
}
inline IrDataType::TypeCase IrDataType::type_case() const {
  return IrDataType::TypeCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::common::GraphDataType_GraphElementOpt> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::common::GraphDataType_GraphElementOpt>() {
  return ::common::GraphDataType_GraphElementOpt_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_type_2eproto
