// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

#include "error.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gs {
namespace neug {
namespace interactive {
}  // namespace interactive
}  // namespace neug
}  // namespace gs
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_error_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_error_2eproto = nullptr;
const uint32_t TableStruct_error_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_error_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013error.proto\022\023gs.neug.interactive*\375\010\n\004C"
  "ode\022\006\n\002OK\020\000\022\023\n\016ERR_PERMISSION\020\351\007\022\033\n\026ERR_"
  "VERSION_MISMATCHED\020\352\007\022\034\n\027ERR_DIRECTORY_N"
  "OT_EXIST\020\353\007\022\030\n\023ERR_DATABASE_LOCKED\020\354\007\022\035\n"
  "\030ERR_DISK_SPACE_EXHAUSTED\020\355\007\022\034\n\027ERR_CORR"
  "UPTION_DETECTED\020\356\007\022\025\n\020ERR_INVALID_PATH\020\357"
  "\007\022\027\n\022ERR_CONFIG_INVALID\020\360\007\022\031\n\024ERR_INVALI"
  "D_ARGUMENT\020\361\007\022\022\n\rERR_NOT_FOUND\020\362\007\022\026\n\021ERR"
  "_NOT_SUPPORTED\020\363\007\022\027\n\022ERR_INTERNAL_ERROR\020"
  "\364\007\022\032\n\025ERR_ILLEGAL_OPERATION\020\365\007\022\021\n\014ERR_IO"
  "_ERROR\020\366\007\022\025\n\020ERR_BAD_ENCODING\020\367\007\022\025\n\020ERR_"
  "INVALID_FILE\020\370\007\022\022\n\rERR_EXTENSION\020\371\007\022\020\n\013E"
  "RR_NETWORK\020\321\017\022\027\n\022ERR_SESSION_CLOSED\020\322\017\022\032"
  "\n\025ERR_CONNECTION_CLOSED\020\323\017\022\027\n\022ERR_POOL_E"
  "XHAUSTED\020\324\017\022\034\n\027ERR_SERVICE_UNAVAILABLE\020\325"
  "\017\022\026\n\021ERR_LOAD_OVERFLOW\020\326\017\022\031\n\024ERR_CONNECT"
  "ION_ERROR\020\327\017\022\024\n\017ERR_COMPILATION\020\270\027\022\030\n\023ER"
  "R_QUERY_EXECUTION\020\271\027\022\025\n\020ERR_QUERY_SYNTAX"
  "\020\272\027\022\026\n\021ERR_QUERY_TIMEOUT\020\273\027\022\031\n\024ERR_CONCU"
  "RRENT_WRITE\020\274\027\022\026\n\021ERR_CODEGEN_ERROR\020\275\027\022\025"
  "\n\020ERR_EMPTY_RESULT\020\276\027\022\030\n\023ERR_NOT_INITIAL"
  "IZED\020\277\027\022\032\n\025ERR_TX_STATE_CONFLICT\020\241\037\022\027\n\022E"
  "RR_WAL_WRITE_FAIL\020\242\037\022\023\n\016ERR_TX_TIMEOUT\020\243"
  "\037\022\030\n\023ERR_SCHEMA_MISMATCH\020\211\'\022\027\n\022ERR_INVAL"
  "ID_SCHEMA\020\212\'\022\030\n\023ERR_TYPE_CONVERSION\020\213\'\022\026"
  "\n\021ERR_TYPE_OVERFLOW\020\214\'\022\024\n\017ERR_INDEX_ERRO"
  "R\020\215\'\022\025\n\020ERR_PLATFORM_ABI\020\361.\022\025\n\020ERR_PY_BI"
  "ND_INIT\020\362.\022\026\n\021ERR_ARCH_MISMATCH\020\363.\022\032\n\025ER"
  "R_DEPLOY_DEPENDENCY\020\364.\022\030\n\023ERR_NOT_IMPLEM"
  "ENTED\020\3316\022\020\n\013ERR_UNKNOWN\020\217NB,\n(com.alibab"
  "a.graphscope.interactive.protoP\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_error_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_error_2eproto = {
    false, false, 1240, descriptor_table_protodef_error_2eproto,
    "error.proto",
    &descriptor_table_error_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_error_2eproto::offsets,
    nullptr, file_level_enum_descriptors_error_2eproto,
    file_level_service_descriptors_error_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_error_2eproto_getter() {
  return &descriptor_table_error_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_error_2eproto(&descriptor_table_error_2eproto);
namespace gs {
namespace neug {
namespace interactive {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Code_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_error_2eproto);
  return file_level_enum_descriptors_error_2eproto[0];
}
bool Code_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
    case 1015:
    case 1016:
    case 1017:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 3000:
    case 3001:
    case 3002:
    case 3003:
    case 3004:
    case 3005:
    case 3006:
    case 3007:
    case 4001:
    case 4002:
    case 4003:
    case 5001:
    case 5002:
    case 5003:
    case 5004:
    case 5005:
    case 6001:
    case 6002:
    case 6003:
    case 6004:
    case 7001:
    case 9999:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace interactive
}  // namespace neug
}  // namespace gs
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
