// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

#include "schema.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace schema {
PROTOBUF_CONSTEXPR LabelMeta::LabelMeta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LabelMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LabelMetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LabelMetaDefaultTypeInternal() {}
  union {
    LabelMeta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LabelMetaDefaultTypeInternal _LabelMeta_default_instance_;
PROTOBUF_CONSTEXPR ColumnMeta::ColumnMeta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/nullptr
  , /*decltype(_impl_.data_type_)*/nullptr
  , /*decltype(_impl_.is_primary_key_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ColumnMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ColumnMetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ColumnMetaDefaultTypeInternal() {}
  union {
    ColumnMeta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ColumnMetaDefaultTypeInternal _ColumnMeta_default_instance_;
PROTOBUF_CONSTEXPR EntityMeta::EntityMeta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.columns_)*/{}
  , /*decltype(_impl_.label_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct EntityMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EntityMetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EntityMetaDefaultTypeInternal() {}
  union {
    EntityMeta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EntityMetaDefaultTypeInternal _EntityMeta_default_instance_;
PROTOBUF_CONSTEXPR RelationMeta_LabelPair::RelationMeta_LabelPair(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.src_)*/nullptr
  , /*decltype(_impl_.dst_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RelationMeta_LabelPairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelationMeta_LabelPairDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelationMeta_LabelPairDefaultTypeInternal() {}
  union {
    RelationMeta_LabelPair _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelationMeta_LabelPairDefaultTypeInternal _RelationMeta_LabelPair_default_instance_;
PROTOBUF_CONSTEXPR RelationMeta::RelationMeta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_pairs_)*/{}
  , /*decltype(_impl_.columns_)*/{}
  , /*decltype(_impl_.label_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RelationMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelationMetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelationMetaDefaultTypeInternal() {}
  union {
    RelationMeta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelationMetaDefaultTypeInternal _RelationMeta_default_instance_;
PROTOBUF_CONSTEXPR Schema::Schema(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entities_)*/{}
  , /*decltype(_impl_.relations_)*/{}
  , /*decltype(_impl_.is_table_id_)*/false
  , /*decltype(_impl_.is_column_id_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SchemaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SchemaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SchemaDefaultTypeInternal() {}
  union {
    Schema _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SchemaDefaultTypeInternal _Schema_default_instance_;
}  // namespace schema
static ::_pb::Metadata file_level_metadata_schema_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_schema_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_schema_2eproto = nullptr;

const uint32_t TableStruct_schema_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::LabelMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::LabelMeta, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::schema::LabelMeta, _impl_.name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::ColumnMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::ColumnMeta, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::schema::ColumnMeta, _impl_.data_type_),
  PROTOBUF_FIELD_OFFSET(::schema::ColumnMeta, _impl_.is_primary_key_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::EntityMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::EntityMeta, _impl_.label_),
  PROTOBUF_FIELD_OFFSET(::schema::EntityMeta, _impl_.columns_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta_LabelPair, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta_LabelPair, _impl_.src_),
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta_LabelPair, _impl_.dst_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta, _impl_.label_),
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta, _impl_.entity_pairs_),
  PROTOBUF_FIELD_OFFSET(::schema::RelationMeta, _impl_.columns_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::schema::Schema, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::schema::Schema, _impl_.entities_),
  PROTOBUF_FIELD_OFFSET(::schema::Schema, _impl_.relations_),
  PROTOBUF_FIELD_OFFSET(::schema::Schema, _impl_.is_table_id_),
  PROTOBUF_FIELD_OFFSET(::schema::Schema, _impl_.is_column_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::schema::LabelMeta)},
  { 8, -1, -1, sizeof(::schema::ColumnMeta)},
  { 17, -1, -1, sizeof(::schema::EntityMeta)},
  { 25, -1, -1, sizeof(::schema::RelationMeta_LabelPair)},
  { 33, -1, -1, sizeof(::schema::RelationMeta)},
  { 42, -1, -1, sizeof(::schema::Schema)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::schema::_LabelMeta_default_instance_._instance,
  &::schema::_ColumnMeta_default_instance_._instance,
  &::schema::_EntityMeta_default_instance_._instance,
  &::schema::_RelationMeta_LabelPair_default_instance_._instance,
  &::schema::_RelationMeta_default_instance_._instance,
  &::schema::_Schema_default_instance_._instance,
};

const char descriptor_table_protodef_schema_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014schema.proto\022\006schema\032\014common.proto\032\020ba"
  "sic_type.proto\"%\n\tLabelMeta\022\n\n\002id\030\001 \001(\005\022"
  "\014\n\004name\030\002 \001(\t\"i\n\nColumnMeta\022\036\n\003key\030\001 \001(\013"
  "2\021.schema.LabelMeta\022#\n\tdata_type\030\002 \001(\0132\020"
  ".common.DataType\022\026\n\016is_primary_key\030\003 \001(\010"
  "\"S\n\nEntityMeta\022 \n\005label\030\001 \001(\0132\021.schema.L"
  "abelMeta\022#\n\007columns\030\002 \003(\0132\022.schema.Colum"
  "nMeta\"\330\001\n\014RelationMeta\022 \n\005label\030\001 \001(\0132\021."
  "schema.LabelMeta\0224\n\014entity_pairs\030\002 \003(\0132\036"
  ".schema.RelationMeta.LabelPair\022#\n\007column"
  "s\030\003 \003(\0132\022.schema.ColumnMeta\032K\n\tLabelPair"
  "\022\036\n\003src\030\001 \001(\0132\021.schema.LabelMeta\022\036\n\003dst\030"
  "\002 \001(\0132\021.schema.LabelMeta\"\202\001\n\006Schema\022$\n\010e"
  "ntities\030\001 \003(\0132\022.schema.EntityMeta\022\'\n\trel"
  "ations\030\002 \003(\0132\024.schema.RelationMeta\022\023\n\013is"
  "_table_id\030\003 \001(\010\022\024\n\014is_column_id\030\004 \001(\010B0\n"
  "!com.alibaba.graphscope.gaia.protoB\013Oute"
  "rSchemab\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_schema_2eproto_deps[2] = {
  &::descriptor_table_basic_5ftype_2eproto,
  &::descriptor_table_common_2eproto,
};
static ::_pbi::once_flag descriptor_table_schema_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_schema_2eproto = {
    false, false, 695, descriptor_table_protodef_schema_2eproto,
    "schema.proto",
    &descriptor_table_schema_2eproto_once, descriptor_table_schema_2eproto_deps, 2, 6,
    schemas, file_default_instances, TableStruct_schema_2eproto::offsets,
    file_level_metadata_schema_2eproto, file_level_enum_descriptors_schema_2eproto,
    file_level_service_descriptors_schema_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_schema_2eproto_getter() {
  return &descriptor_table_schema_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_schema_2eproto(&descriptor_table_schema_2eproto);
namespace schema {

// ===================================================================

class LabelMeta::_Internal {
 public:
};

LabelMeta::LabelMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.LabelMeta)
}
LabelMeta::LabelMeta(const LabelMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LabelMeta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:schema.LabelMeta)
}

inline void LabelMeta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LabelMeta::~LabelMeta() {
  // @@protoc_insertion_point(destructor:schema.LabelMeta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LabelMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void LabelMeta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LabelMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.LabelMeta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LabelMeta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "schema.LabelMeta.name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LabelMeta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.LabelMeta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "schema.LabelMeta.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.LabelMeta)
  return target;
}

size_t LabelMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.LabelMeta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LabelMeta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LabelMeta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LabelMeta::GetClassData() const { return &_class_data_; }


void LabelMeta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LabelMeta*>(&to_msg);
  auto& from = static_cast<const LabelMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.LabelMeta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LabelMeta::CopyFrom(const LabelMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.LabelMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LabelMeta::IsInitialized() const {
  return true;
}

void LabelMeta::InternalSwap(LabelMeta* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LabelMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[0]);
}

// ===================================================================

class ColumnMeta::_Internal {
 public:
  static const ::schema::LabelMeta& key(const ColumnMeta* msg);
  static const ::common::DataType& data_type(const ColumnMeta* msg);
};

const ::schema::LabelMeta&
ColumnMeta::_Internal::key(const ColumnMeta* msg) {
  return *msg->_impl_.key_;
}
const ::common::DataType&
ColumnMeta::_Internal::data_type(const ColumnMeta* msg) {
  return *msg->_impl_.data_type_;
}
void ColumnMeta::clear_data_type() {
  if (GetArenaForAllocation() == nullptr && _impl_.data_type_ != nullptr) {
    delete _impl_.data_type_;
  }
  _impl_.data_type_ = nullptr;
}
ColumnMeta::ColumnMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.ColumnMeta)
}
ColumnMeta::ColumnMeta(const ColumnMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ColumnMeta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){nullptr}
    , decltype(_impl_.data_type_){nullptr}
    , decltype(_impl_.is_primary_key_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_key()) {
    _this->_impl_.key_ = new ::schema::LabelMeta(*from._impl_.key_);
  }
  if (from._internal_has_data_type()) {
    _this->_impl_.data_type_ = new ::common::DataType(*from._impl_.data_type_);
  }
  _this->_impl_.is_primary_key_ = from._impl_.is_primary_key_;
  // @@protoc_insertion_point(copy_constructor:schema.ColumnMeta)
}

inline void ColumnMeta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){nullptr}
    , decltype(_impl_.data_type_){nullptr}
    , decltype(_impl_.is_primary_key_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ColumnMeta::~ColumnMeta() {
  // @@protoc_insertion_point(destructor:schema.ColumnMeta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ColumnMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.key_;
  if (this != internal_default_instance()) delete _impl_.data_type_;
}

void ColumnMeta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ColumnMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.ColumnMeta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.key_ != nullptr) {
    delete _impl_.key_;
  }
  _impl_.key_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.data_type_ != nullptr) {
    delete _impl_.data_type_;
  }
  _impl_.data_type_ = nullptr;
  _impl_.is_primary_key_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ColumnMeta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .schema.LabelMeta key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_key(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .common.DataType data_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_data_type(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_primary_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.is_primary_key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ColumnMeta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.ColumnMeta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .schema.LabelMeta key = 1;
  if (this->_internal_has_key()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::key(this),
        _Internal::key(this).GetCachedSize(), target, stream);
  }

  // .common.DataType data_type = 2;
  if (this->_internal_has_data_type()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::data_type(this),
        _Internal::data_type(this).GetCachedSize(), target, stream);
  }

  // bool is_primary_key = 3;
  if (this->_internal_is_primary_key() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_is_primary_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.ColumnMeta)
  return target;
}

size_t ColumnMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.ColumnMeta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .schema.LabelMeta key = 1;
  if (this->_internal_has_key()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.key_);
  }

  // .common.DataType data_type = 2;
  if (this->_internal_has_data_type()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.data_type_);
  }

  // bool is_primary_key = 3;
  if (this->_internal_is_primary_key() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ColumnMeta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ColumnMeta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ColumnMeta::GetClassData() const { return &_class_data_; }


void ColumnMeta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ColumnMeta*>(&to_msg);
  auto& from = static_cast<const ColumnMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.ColumnMeta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_key()) {
    _this->_internal_mutable_key()->::schema::LabelMeta::MergeFrom(
        from._internal_key());
  }
  if (from._internal_has_data_type()) {
    _this->_internal_mutable_data_type()->::common::DataType::MergeFrom(
        from._internal_data_type());
  }
  if (from._internal_is_primary_key() != 0) {
    _this->_internal_set_is_primary_key(from._internal_is_primary_key());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ColumnMeta::CopyFrom(const ColumnMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.ColumnMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ColumnMeta::IsInitialized() const {
  return true;
}

void ColumnMeta::InternalSwap(ColumnMeta* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ColumnMeta, _impl_.is_primary_key_)
      + sizeof(ColumnMeta::_impl_.is_primary_key_)
      - PROTOBUF_FIELD_OFFSET(ColumnMeta, _impl_.key_)>(
          reinterpret_cast<char*>(&_impl_.key_),
          reinterpret_cast<char*>(&other->_impl_.key_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ColumnMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[1]);
}

// ===================================================================

class EntityMeta::_Internal {
 public:
  static const ::schema::LabelMeta& label(const EntityMeta* msg);
};

const ::schema::LabelMeta&
EntityMeta::_Internal::label(const EntityMeta* msg) {
  return *msg->_impl_.label_;
}
EntityMeta::EntityMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.EntityMeta)
}
EntityMeta::EntityMeta(const EntityMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EntityMeta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.columns_){from._impl_.columns_}
    , decltype(_impl_.label_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_label()) {
    _this->_impl_.label_ = new ::schema::LabelMeta(*from._impl_.label_);
  }
  // @@protoc_insertion_point(copy_constructor:schema.EntityMeta)
}

inline void EntityMeta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.columns_){arena}
    , decltype(_impl_.label_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

EntityMeta::~EntityMeta() {
  // @@protoc_insertion_point(destructor:schema.EntityMeta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EntityMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.columns_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.label_;
}

void EntityMeta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EntityMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.EntityMeta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.columns_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.label_ != nullptr) {
    delete _impl_.label_;
  }
  _impl_.label_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EntityMeta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .schema.LabelMeta label = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_label(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .schema.ColumnMeta columns = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_columns(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EntityMeta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.EntityMeta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .schema.LabelMeta label = 1;
  if (this->_internal_has_label()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::label(this),
        _Internal::label(this).GetCachedSize(), target, stream);
  }

  // repeated .schema.ColumnMeta columns = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_columns_size()); i < n; i++) {
    const auto& repfield = this->_internal_columns(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.EntityMeta)
  return target;
}

size_t EntityMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.EntityMeta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .schema.ColumnMeta columns = 2;
  total_size += 1UL * this->_internal_columns_size();
  for (const auto& msg : this->_impl_.columns_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .schema.LabelMeta label = 1;
  if (this->_internal_has_label()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.label_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EntityMeta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EntityMeta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EntityMeta::GetClassData() const { return &_class_data_; }


void EntityMeta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EntityMeta*>(&to_msg);
  auto& from = static_cast<const EntityMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.EntityMeta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.columns_.MergeFrom(from._impl_.columns_);
  if (from._internal_has_label()) {
    _this->_internal_mutable_label()->::schema::LabelMeta::MergeFrom(
        from._internal_label());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EntityMeta::CopyFrom(const EntityMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.EntityMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EntityMeta::IsInitialized() const {
  return true;
}

void EntityMeta::InternalSwap(EntityMeta* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.columns_.InternalSwap(&other->_impl_.columns_);
  swap(_impl_.label_, other->_impl_.label_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EntityMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[2]);
}

// ===================================================================

class RelationMeta_LabelPair::_Internal {
 public:
  static const ::schema::LabelMeta& src(const RelationMeta_LabelPair* msg);
  static const ::schema::LabelMeta& dst(const RelationMeta_LabelPair* msg);
};

const ::schema::LabelMeta&
RelationMeta_LabelPair::_Internal::src(const RelationMeta_LabelPair* msg) {
  return *msg->_impl_.src_;
}
const ::schema::LabelMeta&
RelationMeta_LabelPair::_Internal::dst(const RelationMeta_LabelPair* msg) {
  return *msg->_impl_.dst_;
}
RelationMeta_LabelPair::RelationMeta_LabelPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.RelationMeta.LabelPair)
}
RelationMeta_LabelPair::RelationMeta_LabelPair(const RelationMeta_LabelPair& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RelationMeta_LabelPair* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.src_){nullptr}
    , decltype(_impl_.dst_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_src()) {
    _this->_impl_.src_ = new ::schema::LabelMeta(*from._impl_.src_);
  }
  if (from._internal_has_dst()) {
    _this->_impl_.dst_ = new ::schema::LabelMeta(*from._impl_.dst_);
  }
  // @@protoc_insertion_point(copy_constructor:schema.RelationMeta.LabelPair)
}

inline void RelationMeta_LabelPair::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.src_){nullptr}
    , decltype(_impl_.dst_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RelationMeta_LabelPair::~RelationMeta_LabelPair() {
  // @@protoc_insertion_point(destructor:schema.RelationMeta.LabelPair)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RelationMeta_LabelPair::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.src_;
  if (this != internal_default_instance()) delete _impl_.dst_;
}

void RelationMeta_LabelPair::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RelationMeta_LabelPair::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.RelationMeta.LabelPair)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.src_ != nullptr) {
    delete _impl_.src_;
  }
  _impl_.src_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.dst_ != nullptr) {
    delete _impl_.dst_;
  }
  _impl_.dst_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RelationMeta_LabelPair::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .schema.LabelMeta src = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_src(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .schema.LabelMeta dst = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_dst(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RelationMeta_LabelPair::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.RelationMeta.LabelPair)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .schema.LabelMeta src = 1;
  if (this->_internal_has_src()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::src(this),
        _Internal::src(this).GetCachedSize(), target, stream);
  }

  // .schema.LabelMeta dst = 2;
  if (this->_internal_has_dst()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::dst(this),
        _Internal::dst(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.RelationMeta.LabelPair)
  return target;
}

size_t RelationMeta_LabelPair::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.RelationMeta.LabelPair)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .schema.LabelMeta src = 1;
  if (this->_internal_has_src()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.src_);
  }

  // .schema.LabelMeta dst = 2;
  if (this->_internal_has_dst()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.dst_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RelationMeta_LabelPair::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RelationMeta_LabelPair::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RelationMeta_LabelPair::GetClassData() const { return &_class_data_; }


void RelationMeta_LabelPair::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RelationMeta_LabelPair*>(&to_msg);
  auto& from = static_cast<const RelationMeta_LabelPair&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.RelationMeta.LabelPair)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_src()) {
    _this->_internal_mutable_src()->::schema::LabelMeta::MergeFrom(
        from._internal_src());
  }
  if (from._internal_has_dst()) {
    _this->_internal_mutable_dst()->::schema::LabelMeta::MergeFrom(
        from._internal_dst());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RelationMeta_LabelPair::CopyFrom(const RelationMeta_LabelPair& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.RelationMeta.LabelPair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RelationMeta_LabelPair::IsInitialized() const {
  return true;
}

void RelationMeta_LabelPair::InternalSwap(RelationMeta_LabelPair* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RelationMeta_LabelPair, _impl_.dst_)
      + sizeof(RelationMeta_LabelPair::_impl_.dst_)
      - PROTOBUF_FIELD_OFFSET(RelationMeta_LabelPair, _impl_.src_)>(
          reinterpret_cast<char*>(&_impl_.src_),
          reinterpret_cast<char*>(&other->_impl_.src_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RelationMeta_LabelPair::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[3]);
}

// ===================================================================

class RelationMeta::_Internal {
 public:
  static const ::schema::LabelMeta& label(const RelationMeta* msg);
};

const ::schema::LabelMeta&
RelationMeta::_Internal::label(const RelationMeta* msg) {
  return *msg->_impl_.label_;
}
RelationMeta::RelationMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.RelationMeta)
}
RelationMeta::RelationMeta(const RelationMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RelationMeta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_pairs_){from._impl_.entity_pairs_}
    , decltype(_impl_.columns_){from._impl_.columns_}
    , decltype(_impl_.label_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_label()) {
    _this->_impl_.label_ = new ::schema::LabelMeta(*from._impl_.label_);
  }
  // @@protoc_insertion_point(copy_constructor:schema.RelationMeta)
}

inline void RelationMeta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_pairs_){arena}
    , decltype(_impl_.columns_){arena}
    , decltype(_impl_.label_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RelationMeta::~RelationMeta() {
  // @@protoc_insertion_point(destructor:schema.RelationMeta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RelationMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entity_pairs_.~RepeatedPtrField();
  _impl_.columns_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.label_;
}

void RelationMeta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RelationMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.RelationMeta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entity_pairs_.Clear();
  _impl_.columns_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.label_ != nullptr) {
    delete _impl_.label_;
  }
  _impl_.label_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RelationMeta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .schema.LabelMeta label = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_label(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .schema.RelationMeta.LabelPair entity_pairs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_entity_pairs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .schema.ColumnMeta columns = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_columns(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RelationMeta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.RelationMeta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .schema.LabelMeta label = 1;
  if (this->_internal_has_label()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::label(this),
        _Internal::label(this).GetCachedSize(), target, stream);
  }

  // repeated .schema.RelationMeta.LabelPair entity_pairs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_entity_pairs_size()); i < n; i++) {
    const auto& repfield = this->_internal_entity_pairs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .schema.ColumnMeta columns = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_columns_size()); i < n; i++) {
    const auto& repfield = this->_internal_columns(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.RelationMeta)
  return target;
}

size_t RelationMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.RelationMeta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .schema.RelationMeta.LabelPair entity_pairs = 2;
  total_size += 1UL * this->_internal_entity_pairs_size();
  for (const auto& msg : this->_impl_.entity_pairs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .schema.ColumnMeta columns = 3;
  total_size += 1UL * this->_internal_columns_size();
  for (const auto& msg : this->_impl_.columns_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .schema.LabelMeta label = 1;
  if (this->_internal_has_label()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.label_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RelationMeta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RelationMeta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RelationMeta::GetClassData() const { return &_class_data_; }


void RelationMeta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RelationMeta*>(&to_msg);
  auto& from = static_cast<const RelationMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.RelationMeta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.entity_pairs_.MergeFrom(from._impl_.entity_pairs_);
  _this->_impl_.columns_.MergeFrom(from._impl_.columns_);
  if (from._internal_has_label()) {
    _this->_internal_mutable_label()->::schema::LabelMeta::MergeFrom(
        from._internal_label());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RelationMeta::CopyFrom(const RelationMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.RelationMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RelationMeta::IsInitialized() const {
  return true;
}

void RelationMeta::InternalSwap(RelationMeta* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entity_pairs_.InternalSwap(&other->_impl_.entity_pairs_);
  _impl_.columns_.InternalSwap(&other->_impl_.columns_);
  swap(_impl_.label_, other->_impl_.label_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RelationMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[4]);
}

// ===================================================================

class Schema::_Internal {
 public:
};

Schema::Schema(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:schema.Schema)
}
Schema::Schema(const Schema& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Schema* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entities_){from._impl_.entities_}
    , decltype(_impl_.relations_){from._impl_.relations_}
    , decltype(_impl_.is_table_id_){}
    , decltype(_impl_.is_column_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.is_table_id_, &from._impl_.is_table_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_column_id_) -
    reinterpret_cast<char*>(&_impl_.is_table_id_)) + sizeof(_impl_.is_column_id_));
  // @@protoc_insertion_point(copy_constructor:schema.Schema)
}

inline void Schema::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entities_){arena}
    , decltype(_impl_.relations_){arena}
    , decltype(_impl_.is_table_id_){false}
    , decltype(_impl_.is_column_id_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Schema::~Schema() {
  // @@protoc_insertion_point(destructor:schema.Schema)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Schema::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entities_.~RepeatedPtrField();
  _impl_.relations_.~RepeatedPtrField();
}

void Schema::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Schema::Clear() {
// @@protoc_insertion_point(message_clear_start:schema.Schema)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entities_.Clear();
  _impl_.relations_.Clear();
  ::memset(&_impl_.is_table_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_column_id_) -
      reinterpret_cast<char*>(&_impl_.is_table_id_)) + sizeof(_impl_.is_column_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Schema::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .schema.EntityMeta entities = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_entities(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .schema.RelationMeta relations = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_relations(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bool is_table_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.is_table_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_column_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.is_column_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Schema::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:schema.Schema)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .schema.EntityMeta entities = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_entities_size()); i < n; i++) {
    const auto& repfield = this->_internal_entities(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .schema.RelationMeta relations = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_relations_size()); i < n; i++) {
    const auto& repfield = this->_internal_relations(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // bool is_table_id = 3;
  if (this->_internal_is_table_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_is_table_id(), target);
  }

  // bool is_column_id = 4;
  if (this->_internal_is_column_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_is_column_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:schema.Schema)
  return target;
}

size_t Schema::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:schema.Schema)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .schema.EntityMeta entities = 1;
  total_size += 1UL * this->_internal_entities_size();
  for (const auto& msg : this->_impl_.entities_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .schema.RelationMeta relations = 2;
  total_size += 1UL * this->_internal_relations_size();
  for (const auto& msg : this->_impl_.relations_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // bool is_table_id = 3;
  if (this->_internal_is_table_id() != 0) {
    total_size += 1 + 1;
  }

  // bool is_column_id = 4;
  if (this->_internal_is_column_id() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Schema::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Schema::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Schema::GetClassData() const { return &_class_data_; }


void Schema::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Schema*>(&to_msg);
  auto& from = static_cast<const Schema&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:schema.Schema)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.entities_.MergeFrom(from._impl_.entities_);
  _this->_impl_.relations_.MergeFrom(from._impl_.relations_);
  if (from._internal_is_table_id() != 0) {
    _this->_internal_set_is_table_id(from._internal_is_table_id());
  }
  if (from._internal_is_column_id() != 0) {
    _this->_internal_set_is_column_id(from._internal_is_column_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Schema::CopyFrom(const Schema& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:schema.Schema)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Schema::IsInitialized() const {
  return true;
}

void Schema::InternalSwap(Schema* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entities_.InternalSwap(&other->_impl_.entities_);
  _impl_.relations_.InternalSwap(&other->_impl_.relations_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Schema, _impl_.is_column_id_)
      + sizeof(Schema::_impl_.is_column_id_)
      - PROTOBUF_FIELD_OFFSET(Schema, _impl_.is_table_id_)>(
          reinterpret_cast<char*>(&_impl_.is_table_id_),
          reinterpret_cast<char*>(&other->_impl_.is_table_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Schema::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_schema_2eproto_getter, &descriptor_table_schema_2eproto_once,
      file_level_metadata_schema_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace schema
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::schema::LabelMeta*
Arena::CreateMaybeMessage< ::schema::LabelMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::LabelMeta >(arena);
}
template<> PROTOBUF_NOINLINE ::schema::ColumnMeta*
Arena::CreateMaybeMessage< ::schema::ColumnMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::ColumnMeta >(arena);
}
template<> PROTOBUF_NOINLINE ::schema::EntityMeta*
Arena::CreateMaybeMessage< ::schema::EntityMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::EntityMeta >(arena);
}
template<> PROTOBUF_NOINLINE ::schema::RelationMeta_LabelPair*
Arena::CreateMaybeMessage< ::schema::RelationMeta_LabelPair >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::RelationMeta_LabelPair >(arena);
}
template<> PROTOBUF_NOINLINE ::schema::RelationMeta*
Arena::CreateMaybeMessage< ::schema::RelationMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::RelationMeta >(arena);
}
template<> PROTOBUF_NOINLINE ::schema::Schema*
Arena::CreateMaybeMessage< ::schema::Schema >(Arena* arena) {
  return Arena::CreateMessageInternal< ::schema::Schema >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
