from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.base_edge_type_vertex_type_pair_relations_inner import BaseEdgeTypeVertexTypePairRelationsInner
from gs_interactive_admin import util

from gs_interactive_admin.models.base_edge_type_vertex_type_pair_relations_inner import BaseEdgeTypeVertexTypePairRelationsInner  # noqa: E501

class BaseEdgeType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type_name=None, primary_keys=None, vertex_type_pair_relations=None):  # noqa: E501
        """BaseEdgeType - a model defined in OpenAPI

        :param type_name: The type_name of this BaseEdgeType.  # noqa: E501
        :type type_name: str
        :param primary_keys: The primary_keys of this BaseEdgeType.  # noqa: E501
        :type primary_keys: List[str]
        :param vertex_type_pair_relations: The vertex_type_pair_relations of this BaseEdgeType.  # noqa: E501
        :type vertex_type_pair_relations: List[BaseEdgeTypeVertexTypePairRelationsInner]
        """
        self.openapi_types = {
            'type_name': str,
            'primary_keys': List[str],
            'vertex_type_pair_relations': List[BaseEdgeTypeVertexTypePairRelationsInner]
        }

        self.attribute_map = {
            'type_name': 'type_name',
            'primary_keys': 'primary_keys',
            'vertex_type_pair_relations': 'vertex_type_pair_relations'
        }

        self._type_name = type_name
        self._primary_keys = primary_keys
        self._vertex_type_pair_relations = vertex_type_pair_relations

    @classmethod
    def from_dict(cls, dikt) -> 'BaseEdgeType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseEdgeType of this BaseEdgeType.  # noqa: E501
        :rtype: BaseEdgeType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type_name(self) -> str:
        """Gets the type_name of this BaseEdgeType.


        :return: The type_name of this BaseEdgeType.
        :rtype: str
        """
        return self._type_name

    @type_name.setter
    def type_name(self, type_name: str):
        """Sets the type_name of this BaseEdgeType.


        :param type_name: The type_name of this BaseEdgeType.
        :type type_name: str
        """

        self._type_name = type_name

    @property
    def primary_keys(self) -> List[str]:
        """Gets the primary_keys of this BaseEdgeType.

        The primary keys of the edge type, which is optional.  # noqa: E501

        :return: The primary_keys of this BaseEdgeType.
        :rtype: List[str]
        """
        return self._primary_keys

    @primary_keys.setter
    def primary_keys(self, primary_keys: List[str]):
        """Sets the primary_keys of this BaseEdgeType.

        The primary keys of the edge type, which is optional.  # noqa: E501

        :param primary_keys: The primary_keys of this BaseEdgeType.
        :type primary_keys: List[str]
        """

        self._primary_keys = primary_keys

    @property
    def vertex_type_pair_relations(self) -> List[BaseEdgeTypeVertexTypePairRelationsInner]:
        """Gets the vertex_type_pair_relations of this BaseEdgeType.


        :return: The vertex_type_pair_relations of this BaseEdgeType.
        :rtype: List[BaseEdgeTypeVertexTypePairRelationsInner]
        """
        return self._vertex_type_pair_relations

    @vertex_type_pair_relations.setter
    def vertex_type_pair_relations(self, vertex_type_pair_relations: List[BaseEdgeTypeVertexTypePairRelationsInner]):
        """Sets the vertex_type_pair_relations of this BaseEdgeType.


        :param vertex_type_pair_relations: The vertex_type_pair_relations of this BaseEdgeType.
        :type vertex_type_pair_relations: List[BaseEdgeTypeVertexTypePairRelationsInner]
        """

        self._vertex_type_pair_relations = vertex_type_pair_relations
