from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.gs_data_type import GSDataType
from gs_interactive_admin import util

from gs_interactive_admin.models.gs_data_type import GSDataType  # noqa: E501

class CreatePropertyMeta(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, property_name=None, property_type=None):  # noqa: E501
        """CreatePropertyMeta - a model defined in OpenAPI

        :param property_name: The property_name of this CreatePropertyMeta.  # noqa: E501
        :type property_name: str
        :param property_type: The property_type of this CreatePropertyMeta.  # noqa: E501
        :type property_type: GSDataType
        """
        self.openapi_types = {
            'property_name': str,
            'property_type': GSDataType
        }

        self.attribute_map = {
            'property_name': 'property_name',
            'property_type': 'property_type'
        }

        self._property_name = property_name
        self._property_type = property_type

    @classmethod
    def from_dict(cls, dikt) -> 'CreatePropertyMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreatePropertyMeta of this CreatePropertyMeta.  # noqa: E501
        :rtype: CreatePropertyMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def property_name(self) -> str:
        """Gets the property_name of this CreatePropertyMeta.


        :return: The property_name of this CreatePropertyMeta.
        :rtype: str
        """
        return self._property_name

    @property_name.setter
    def property_name(self, property_name: str):
        """Sets the property_name of this CreatePropertyMeta.


        :param property_name: The property_name of this CreatePropertyMeta.
        :type property_name: str
        """

        self._property_name = property_name

    @property
    def property_type(self) -> GSDataType:
        """Gets the property_type of this CreatePropertyMeta.


        :return: The property_type of this CreatePropertyMeta.
        :rtype: GSDataType
        """
        return self._property_type

    @property_type.setter
    def property_type(self, property_type: GSDataType):
        """Sets the property_type of this CreatePropertyMeta.


        :param property_type: The property_type of this CreatePropertyMeta.
        :type property_type: GSDataType
        """

        self._property_type = property_type
