from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.model_property import ModelProperty
from gs_interactive_admin import util

from gs_interactive_admin.models.model_property import ModelProperty  # noqa: E501

class DeleteVertexRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, label=None, primary_key_values=None):  # noqa: E501
        """DeleteVertexRequest - a model defined in OpenAPI

        :param label: The label of this DeleteVertexRequest.  # noqa: E501
        :type label: str
        :param primary_key_values: The primary_key_values of this DeleteVertexRequest.  # noqa: E501
        :type primary_key_values: List[ModelProperty]
        """
        self.openapi_types = {
            'label': str,
            'primary_key_values': List[ModelProperty]
        }

        self.attribute_map = {
            'label': 'label',
            'primary_key_values': 'primary_key_values'
        }

        self._label = label
        self._primary_key_values = primary_key_values

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteVertexRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteVertexRequest of this DeleteVertexRequest.  # noqa: E501
        :rtype: DeleteVertexRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self) -> str:
        """Gets the label of this DeleteVertexRequest.

        The label name of the vertex.  # noqa: E501

        :return: The label of this DeleteVertexRequest.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this DeleteVertexRequest.

        The label name of the vertex.  # noqa: E501

        :param label: The label of this DeleteVertexRequest.
        :type label: str
        """

        self._label = label

    @property
    def primary_key_values(self) -> List[ModelProperty]:
        """Gets the primary_key_values of this DeleteVertexRequest.

        Primary key values for the vertex.  # noqa: E501

        :return: The primary_key_values of this DeleteVertexRequest.
        :rtype: List[ModelProperty]
        """
        return self._primary_key_values

    @primary_key_values.setter
    def primary_key_values(self, primary_key_values: List[ModelProperty]):
        """Sets the primary_key_values of this DeleteVertexRequest.

        Primary key values for the vertex.  # noqa: E501

        :param primary_key_values: The primary_key_values of this DeleteVertexRequest.
        :type primary_key_values: List[ModelProperty]
        """

        self._primary_key_values = primary_key_values
