from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.model_property import ModelProperty
from gs_interactive_admin import util

from gs_interactive_admin.models.model_property import ModelProperty  # noqa: E501

class DeleteEdgeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, edge_label=None, src_label=None, dst_label=None, src_primary_key_values=None, dst_primary_key_values=None, properties=None):  # noqa: E501
        """DeleteEdgeRequest - a model defined in OpenAPI

        :param edge_label: The edge_label of this DeleteEdgeRequest.  # noqa: E501
        :type edge_label: str
        :param src_label: The src_label of this DeleteEdgeRequest.  # noqa: E501
        :type src_label: str
        :param dst_label: The dst_label of this DeleteEdgeRequest.  # noqa: E501
        :type dst_label: str
        :param src_primary_key_values: The src_primary_key_values of this DeleteEdgeRequest.  # noqa: E501
        :type src_primary_key_values: List[ModelProperty]
        :param dst_primary_key_values: The dst_primary_key_values of this DeleteEdgeRequest.  # noqa: E501
        :type dst_primary_key_values: List[ModelProperty]
        :param properties: The properties of this DeleteEdgeRequest.  # noqa: E501
        :type properties: List[ModelProperty]
        """
        self.openapi_types = {
            'edge_label': str,
            'src_label': str,
            'dst_label': str,
            'src_primary_key_values': List[ModelProperty],
            'dst_primary_key_values': List[ModelProperty],
            'properties': List[ModelProperty]
        }

        self.attribute_map = {
            'edge_label': 'edge_label',
            'src_label': 'src_label',
            'dst_label': 'dst_label',
            'src_primary_key_values': 'src_primary_key_values',
            'dst_primary_key_values': 'dst_primary_key_values',
            'properties': 'properties'
        }

        self._edge_label = edge_label
        self._src_label = src_label
        self._dst_label = dst_label
        self._src_primary_key_values = src_primary_key_values
        self._dst_primary_key_values = dst_primary_key_values
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteEdgeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteEdgeRequest of this DeleteEdgeRequest.  # noqa: E501
        :rtype: DeleteEdgeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_label(self) -> str:
        """Gets the edge_label of this DeleteEdgeRequest.

        The label name of the edge.  # noqa: E501

        :return: The edge_label of this DeleteEdgeRequest.
        :rtype: str
        """
        return self._edge_label

    @edge_label.setter
    def edge_label(self, edge_label: str):
        """Sets the edge_label of this DeleteEdgeRequest.

        The label name of the edge.  # noqa: E501

        :param edge_label: The edge_label of this DeleteEdgeRequest.
        :type edge_label: str
        """

        self._edge_label = edge_label

    @property
    def src_label(self) -> str:
        """Gets the src_label of this DeleteEdgeRequest.

        The label name of the source vertex.  # noqa: E501

        :return: The src_label of this DeleteEdgeRequest.
        :rtype: str
        """
        return self._src_label

    @src_label.setter
    def src_label(self, src_label: str):
        """Sets the src_label of this DeleteEdgeRequest.

        The label name of the source vertex.  # noqa: E501

        :param src_label: The src_label of this DeleteEdgeRequest.
        :type src_label: str
        """

        self._src_label = src_label

    @property
    def dst_label(self) -> str:
        """Gets the dst_label of this DeleteEdgeRequest.

        The label name of the destination vertex.  # noqa: E501

        :return: The dst_label of this DeleteEdgeRequest.
        :rtype: str
        """
        return self._dst_label

    @dst_label.setter
    def dst_label(self, dst_label: str):
        """Sets the dst_label of this DeleteEdgeRequest.

        The label name of the destination vertex.  # noqa: E501

        :param dst_label: The dst_label of this DeleteEdgeRequest.
        :type dst_label: str
        """

        self._dst_label = dst_label

    @property
    def src_primary_key_values(self) -> List[ModelProperty]:
        """Gets the src_primary_key_values of this DeleteEdgeRequest.

        Primary key values for the source vertex.  # noqa: E501

        :return: The src_primary_key_values of this DeleteEdgeRequest.
        :rtype: List[ModelProperty]
        """
        return self._src_primary_key_values

    @src_primary_key_values.setter
    def src_primary_key_values(self, src_primary_key_values: List[ModelProperty]):
        """Sets the src_primary_key_values of this DeleteEdgeRequest.

        Primary key values for the source vertex.  # noqa: E501

        :param src_primary_key_values: The src_primary_key_values of this DeleteEdgeRequest.
        :type src_primary_key_values: List[ModelProperty]
        """

        self._src_primary_key_values = src_primary_key_values

    @property
    def dst_primary_key_values(self) -> List[ModelProperty]:
        """Gets the dst_primary_key_values of this DeleteEdgeRequest.

        Primary key values for the destination vertex.  # noqa: E501

        :return: The dst_primary_key_values of this DeleteEdgeRequest.
        :rtype: List[ModelProperty]
        """
        return self._dst_primary_key_values

    @dst_primary_key_values.setter
    def dst_primary_key_values(self, dst_primary_key_values: List[ModelProperty]):
        """Sets the dst_primary_key_values of this DeleteEdgeRequest.

        Primary key values for the destination vertex.  # noqa: E501

        :param dst_primary_key_values: The dst_primary_key_values of this DeleteEdgeRequest.
        :type dst_primary_key_values: List[ModelProperty]
        """

        self._dst_primary_key_values = dst_primary_key_values

    @property
    def properties(self) -> List[ModelProperty]:
        """Gets the properties of this DeleteEdgeRequest.

        The properties of the edge. If the edge type has primary key, it should be included in the properties.  # noqa: E501

        :return: The properties of this DeleteEdgeRequest.
        :rtype: List[ModelProperty]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: List[ModelProperty]):
        """Sets the properties of this DeleteEdgeRequest.

        The properties of the edge. If the edge type has primary key, it should be included in the properties.  # noqa: E501

        :param properties: The properties of this DeleteEdgeRequest.
        :type properties: List[ModelProperty]
        """

        self._properties = properties
