from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.schema_mapping_loading_config_data_source import SchemaMappingLoadingConfigDataSource
from gs_interactive_admin.models.schema_mapping_loading_config_format import SchemaMappingLoadingConfigFormat
from gs_interactive_admin.models.schema_mapping_loading_config_x_csr_params import SchemaMappingLoadingConfigXCsrParams
from gs_interactive_admin import util

from gs_interactive_admin.models.schema_mapping_loading_config_data_source import SchemaMappingLoadingConfigDataSource  # noqa: E501
from gs_interactive_admin.models.schema_mapping_loading_config_format import SchemaMappingLoadingConfigFormat  # noqa: E501
from gs_interactive_admin.models.schema_mapping_loading_config_x_csr_params import SchemaMappingLoadingConfigXCsrParams  # noqa: E501

class SchemaMappingLoadingConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x_csr_params=None, data_source=None, import_option=None, format=None, destination=None):  # noqa: E501
        """SchemaMappingLoadingConfig - a model defined in OpenAPI

        :param x_csr_params: The x_csr_params of this SchemaMappingLoadingConfig.  # noqa: E501
        :type x_csr_params: SchemaMappingLoadingConfigXCsrParams
        :param data_source: The data_source of this SchemaMappingLoadingConfig.  # noqa: E501
        :type data_source: SchemaMappingLoadingConfigDataSource
        :param import_option: The import_option of this SchemaMappingLoadingConfig.  # noqa: E501
        :type import_option: str
        :param format: The format of this SchemaMappingLoadingConfig.  # noqa: E501
        :type format: SchemaMappingLoadingConfigFormat
        :param destination: The destination of this SchemaMappingLoadingConfig.  # noqa: E501
        :type destination: str
        """
        self.openapi_types = {
            'x_csr_params': SchemaMappingLoadingConfigXCsrParams,
            'data_source': SchemaMappingLoadingConfigDataSource,
            'import_option': str,
            'format': SchemaMappingLoadingConfigFormat,
            'destination': str
        }

        self.attribute_map = {
            'x_csr_params': 'x_csr_params',
            'data_source': 'data_source',
            'import_option': 'import_option',
            'format': 'format',
            'destination': 'destination'
        }

        self._x_csr_params = x_csr_params
        self._data_source = data_source
        self._import_option = import_option
        self._format = format
        self._destination = destination

    @classmethod
    def from_dict(cls, dikt) -> 'SchemaMappingLoadingConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SchemaMapping_loading_config of this SchemaMappingLoadingConfig.  # noqa: E501
        :rtype: SchemaMappingLoadingConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x_csr_params(self) -> SchemaMappingLoadingConfigXCsrParams:
        """Gets the x_csr_params of this SchemaMappingLoadingConfig.


        :return: The x_csr_params of this SchemaMappingLoadingConfig.
        :rtype: SchemaMappingLoadingConfigXCsrParams
        """
        return self._x_csr_params

    @x_csr_params.setter
    def x_csr_params(self, x_csr_params: SchemaMappingLoadingConfigXCsrParams):
        """Sets the x_csr_params of this SchemaMappingLoadingConfig.


        :param x_csr_params: The x_csr_params of this SchemaMappingLoadingConfig.
        :type x_csr_params: SchemaMappingLoadingConfigXCsrParams
        """

        self._x_csr_params = x_csr_params

    @property
    def data_source(self) -> SchemaMappingLoadingConfigDataSource:
        """Gets the data_source of this SchemaMappingLoadingConfig.


        :return: The data_source of this SchemaMappingLoadingConfig.
        :rtype: SchemaMappingLoadingConfigDataSource
        """
        return self._data_source

    @data_source.setter
    def data_source(self, data_source: SchemaMappingLoadingConfigDataSource):
        """Sets the data_source of this SchemaMappingLoadingConfig.


        :param data_source: The data_source of this SchemaMappingLoadingConfig.
        :type data_source: SchemaMappingLoadingConfigDataSource
        """

        self._data_source = data_source

    @property
    def import_option(self) -> str:
        """Gets the import_option of this SchemaMappingLoadingConfig.


        :return: The import_option of this SchemaMappingLoadingConfig.
        :rtype: str
        """
        return self._import_option

    @import_option.setter
    def import_option(self, import_option: str):
        """Sets the import_option of this SchemaMappingLoadingConfig.


        :param import_option: The import_option of this SchemaMappingLoadingConfig.
        :type import_option: str
        """
        allowed_values = ["init", "overwrite"]  # noqa: E501
        if import_option not in allowed_values:
            raise ValueError(
                "Invalid value for `import_option` ({0}), must be one of {1}"
                .format(import_option, allowed_values)
            )

        self._import_option = import_option

    @property
    def format(self) -> SchemaMappingLoadingConfigFormat:
        """Gets the format of this SchemaMappingLoadingConfig.


        :return: The format of this SchemaMappingLoadingConfig.
        :rtype: SchemaMappingLoadingConfigFormat
        """
        return self._format

    @format.setter
    def format(self, format: SchemaMappingLoadingConfigFormat):
        """Sets the format of this SchemaMappingLoadingConfig.


        :param format: The format of this SchemaMappingLoadingConfig.
        :type format: SchemaMappingLoadingConfigFormat
        """

        self._format = format

    @property
    def destination(self) -> str:
        """Gets the destination of this SchemaMappingLoadingConfig.


        :return: The destination of this SchemaMappingLoadingConfig.
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination: str):
        """Sets the destination of this SchemaMappingLoadingConfig.


        :param destination: The destination of this SchemaMappingLoadingConfig.
        :type destination: str
        """

        self._destination = destination
