from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.registry_instance_record import RegistryInstanceRecord
from gs_interactive_admin import util

from gs_interactive_admin.models.registry_instance_record import RegistryInstanceRecord  # noqa: E501

class ServiceRegistryRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_name=None, instances=None, primary=None):  # noqa: E501
        """ServiceRegistryRecord - a model defined in OpenAPI

        :param service_name: The service_name of this ServiceRegistryRecord.  # noqa: E501
        :type service_name: str
        :param instances: The instances of this ServiceRegistryRecord.  # noqa: E501
        :type instances: List[RegistryInstanceRecord]
        :param primary: The primary of this ServiceRegistryRecord.  # noqa: E501
        :type primary: RegistryInstanceRecord
        """
        self.openapi_types = {
            'service_name': str,
            'instances': List[RegistryInstanceRecord],
            'primary': RegistryInstanceRecord
        }

        self.attribute_map = {
            'service_name': 'service_name',
            'instances': 'instances',
            'primary': 'primary'
        }

        self._service_name = service_name
        self._instances = instances
        self._primary = primary

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceRegistryRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceRegistryRecord of this ServiceRegistryRecord.  # noqa: E501
        :rtype: ServiceRegistryRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_name(self) -> str:
        """Gets the service_name of this ServiceRegistryRecord.


        :return: The service_name of this ServiceRegistryRecord.
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name: str):
        """Sets the service_name of this ServiceRegistryRecord.


        :param service_name: The service_name of this ServiceRegistryRecord.
        :type service_name: str
        """

        self._service_name = service_name

    @property
    def instances(self) -> List[RegistryInstanceRecord]:
        """Gets the instances of this ServiceRegistryRecord.


        :return: The instances of this ServiceRegistryRecord.
        :rtype: List[RegistryInstanceRecord]
        """
        return self._instances

    @instances.setter
    def instances(self, instances: List[RegistryInstanceRecord]):
        """Sets the instances of this ServiceRegistryRecord.


        :param instances: The instances of this ServiceRegistryRecord.
        :type instances: List[RegistryInstanceRecord]
        """

        self._instances = instances

    @property
    def primary(self) -> RegistryInstanceRecord:
        """Gets the primary of this ServiceRegistryRecord.


        :return: The primary of this ServiceRegistryRecord.
        :rtype: RegistryInstanceRecord
        """
        return self._primary

    @primary.setter
    def primary(self, primary: RegistryInstanceRecord):
        """Sets the primary of this ServiceRegistryRecord.


        :param primary: The primary of this ServiceRegistryRecord.
        :type primary: RegistryInstanceRecord
        """

        self._primary = primary
