from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin import util


class VertexTypePairStatistics(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source_vertex=None, destination_vertex=None, count=None):  # noqa: E501
        """VertexTypePairStatistics - a model defined in OpenAPI

        :param source_vertex: The source_vertex of this VertexTypePairStatistics.  # noqa: E501
        :type source_vertex: str
        :param destination_vertex: The destination_vertex of this VertexTypePairStatistics.  # noqa: E501
        :type destination_vertex: str
        :param count: The count of this VertexTypePairStatistics.  # noqa: E501
        :type count: int
        """
        self.openapi_types = {
            'source_vertex': str,
            'destination_vertex': str,
            'count': int
        }

        self.attribute_map = {
            'source_vertex': 'source_vertex',
            'destination_vertex': 'destination_vertex',
            'count': 'count'
        }

        self._source_vertex = source_vertex
        self._destination_vertex = destination_vertex
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'VertexTypePairStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VertexTypePairStatistics of this VertexTypePairStatistics.  # noqa: E501
        :rtype: VertexTypePairStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_vertex(self) -> str:
        """Gets the source_vertex of this VertexTypePairStatistics.


        :return: The source_vertex of this VertexTypePairStatistics.
        :rtype: str
        """
        return self._source_vertex

    @source_vertex.setter
    def source_vertex(self, source_vertex: str):
        """Sets the source_vertex of this VertexTypePairStatistics.


        :param source_vertex: The source_vertex of this VertexTypePairStatistics.
        :type source_vertex: str
        """
        if source_vertex is None:
            raise ValueError("Invalid value for `source_vertex`, must not be `None`")  # noqa: E501

        self._source_vertex = source_vertex

    @property
    def destination_vertex(self) -> str:
        """Gets the destination_vertex of this VertexTypePairStatistics.


        :return: The destination_vertex of this VertexTypePairStatistics.
        :rtype: str
        """
        return self._destination_vertex

    @destination_vertex.setter
    def destination_vertex(self, destination_vertex: str):
        """Sets the destination_vertex of this VertexTypePairStatistics.


        :param destination_vertex: The destination_vertex of this VertexTypePairStatistics.
        :type destination_vertex: str
        """
        if destination_vertex is None:
            raise ValueError("Invalid value for `destination_vertex`, must not be `None`")  # noqa: E501

        self._destination_vertex = destination_vertex

    @property
    def count(self) -> int:
        """Gets the count of this VertexTypePairStatistics.


        :return: The count of this VertexTypePairStatistics.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this VertexTypePairStatistics.


        :param count: The count of this VertexTypePairStatistics.
        :type count: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count
