from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from gs_interactive_admin.models.base_model import Model
from gs_interactive_admin.models.model_property import ModelProperty
from gs_interactive_admin import util

from gs_interactive_admin.models.model_property import ModelProperty  # noqa: E501

class VertexRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, label=None, primary_key_values=None, properties=None):  # noqa: E501
        """VertexRequest - a model defined in OpenAPI

        :param label: The label of this VertexRequest.  # noqa: E501
        :type label: str
        :param primary_key_values: The primary_key_values of this VertexRequest.  # noqa: E501
        :type primary_key_values: List[ModelProperty]
        :param properties: The properties of this VertexRequest.  # noqa: E501
        :type properties: List[ModelProperty]
        """
        self.openapi_types = {
            'label': str,
            'primary_key_values': List[ModelProperty],
            'properties': List[ModelProperty]
        }

        self.attribute_map = {
            'label': 'label',
            'primary_key_values': 'primary_key_values',
            'properties': 'properties'
        }

        self._label = label
        self._primary_key_values = primary_key_values
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'VertexRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VertexRequest of this VertexRequest.  # noqa: E501
        :rtype: VertexRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self) -> str:
        """Gets the label of this VertexRequest.


        :return: The label of this VertexRequest.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this VertexRequest.


        :param label: The label of this VertexRequest.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def primary_key_values(self) -> List[ModelProperty]:
        """Gets the primary_key_values of this VertexRequest.


        :return: The primary_key_values of this VertexRequest.
        :rtype: List[ModelProperty]
        """
        return self._primary_key_values

    @primary_key_values.setter
    def primary_key_values(self, primary_key_values: List[ModelProperty]):
        """Sets the primary_key_values of this VertexRequest.


        :param primary_key_values: The primary_key_values of this VertexRequest.
        :type primary_key_values: List[ModelProperty]
        """
        if primary_key_values is None:
            raise ValueError("Invalid value for `primary_key_values`, must not be `None`")  # noqa: E501

        self._primary_key_values = primary_key_values

    @property
    def properties(self) -> List[ModelProperty]:
        """Gets the properties of this VertexRequest.


        :return: The properties of this VertexRequest.
        :rtype: List[ModelProperty]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: List[ModelProperty]):
        """Sets the properties of this VertexRequest.


        :param properties: The properties of this VertexRequest.
        :type properties: List[ModelProperty]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties
