# coding: utf-8

"""
    GraphScope Interactive API v0.3

    This is the definition of GraphScope Interactive API, including   - AdminService API   - Vertex/Edge API   - QueryService   AdminService API (with tag AdminService) defines the API for GraphManagement, ProcedureManagement and Service Management.  Vertex/Edge API (with tag GraphService) defines the API for Vertex/Edge management, including creation/updating/delete/retrieve.  QueryService API (with tag QueryService) defines the API for procedure_call, Ahodc query. 

    The version of the OpenAPI document: 1.0.0
    Contact: graphscope@alibaba-inc.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from gs_interactive.models.model_property import ModelProperty
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EdgeRequest(BaseModel):
    """
    EdgeRequest
    """ # noqa: E501
    src_label: StrictStr
    dst_label: StrictStr
    edge_label: StrictStr
    src_primary_key_values: List[ModelProperty]
    dst_primary_key_values: List[ModelProperty]
    properties: Optional[List[ModelProperty]] = None
    __properties: ClassVar[List[str]] = ["src_label", "dst_label", "edge_label", "src_primary_key_values", "dst_primary_key_values", "properties"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EdgeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in src_primary_key_values (list)
        _items = []
        if self.src_primary_key_values:
            for _item in self.src_primary_key_values:
                if _item:
                    _items.append(_item.to_dict())
            _dict['src_primary_key_values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dst_primary_key_values (list)
        _items = []
        if self.dst_primary_key_values:
            for _item in self.dst_primary_key_values:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dst_primary_key_values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in properties (list)
        _items = []
        if self.properties:
            for _item in self.properties:
                if _item:
                    _items.append(_item.to_dict())
            _dict['properties'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EdgeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "src_label": obj.get("src_label"),
            "dst_label": obj.get("dst_label"),
            "edge_label": obj.get("edge_label"),
            "src_primary_key_values": [ModelProperty.from_dict(_item) for _item in obj.get("src_primary_key_values")] if obj.get("src_primary_key_values") is not None else None,
            "dst_primary_key_values": [ModelProperty.from_dict(_item) for _item in obj.get("dst_primary_key_values")] if obj.get("dst_primary_key_values") is not None else None,
            "properties": [ModelProperty.from_dict(_item) for _item in obj.get("properties")] if obj.get("properties") is not None else None
        })
        return _obj


