/**
 * Copyright 2020 Alibaba Group Holding Limited. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Error codes mirror the protobuf `Code` enum defined in `proto/error.proto`.
 * Provides both numeric constants and a reverse mapping from code to name.
 *
 * @module error-codes
 */

'use strict';

// ---- Numeric error code constants (from error.proto Code enum) ----
// General errors (1001-1017)
const OK = 0;
const ERR_PERMISSION = 1001;
const ERR_VERSION_MISMATCHED = 1002;
const ERR_DIRECTORY_NOT_EXIST = 1003;
const ERR_DATABASE_LOCKED = 1004;
const ERR_DISK_SPACE_EXHAUSTED = 1005;
const ERR_CORRUPTION_DETECTED = 1006;
const ERR_INVALID_PATH = 1007;
const ERR_CONFIG_INVALID = 1008;
const ERR_INVALID_ARGUMENT = 1009;
const ERR_NOT_FOUND = 1010;
const ERR_NOT_SUPPORTED = 1011;
const ERR_INTERNAL_ERROR = 1012;
const ERR_ILLEGAL_OPERATION = 1013;
const ERR_IO_ERROR = 1014;
const ERR_BAD_ENCODING = 1015;
const ERR_INVALID_FILE = 1016;
const ERR_EXTENSION = 1017;

// Network errors (2001-2007)
const ERR_NETWORK = 2001;
const ERR_SESSION_CLOSED = 2002;
const ERR_CONNECTION_CLOSED = 2003;
const ERR_POOL_EXHAUSTED = 2004;
const ERR_SERVICE_UNAVAILABLE = 2005;
const ERR_LOAD_OVERFLOW = 2006;
const ERR_CONNECTION_ERROR = 2007;

// Query errors (3000-3007)
const ERR_COMPILATION = 3000;
const ERR_QUERY_EXECUTION = 3001;
const ERR_QUERY_SYNTAX = 3002;
const ERR_QUERY_TIMEOUT = 3003;
const ERR_CONCURRENT_WRITE = 3004;
const ERR_CODEGEN_ERROR = 3005;
const ERR_EMPTY_RESULT = 3006;
const ERR_NOT_INITIALIZED = 3007;

// Transaction errors (4001-4003)
const ERR_TX_STATE_CONFLICT = 4001;
const ERR_WAL_WRITE_FAIL = 4002;
const ERR_TX_TIMEOUT = 4003;

// Schema errors (5001-5005)
const ERR_SCHEMA_MISMATCH = 5001;
const ERR_INVALID_SCHEMA = 5002;
const ERR_TYPE_CONVERSION = 5003;
const ERR_TYPE_OVERFLOW = 5004;
const ERR_INDEX_ERROR = 5005;

// Deployment errors (6001-6004)
const ERR_PLATFORM_ABI = 6001;
const ERR_PY_BIND_INIT = 6002;
const ERR_ARCH_MISMATCH = 6003;
const ERR_DEPLOY_DEPENDENCY = 6004;

// Not implemented (7001)
const ERR_NOT_IMPLEMENTED = 7001;

// Unknown (9999)
const ERR_UNKNOWN = 9999;

// ---- Code enum: maps numeric code → name string ----
const Code = {
  [OK]: 'OK',
  [ERR_PERMISSION]: 'ERR_PERMISSION',
  [ERR_VERSION_MISMATCHED]: 'ERR_VERSION_MISMATCHED',
  [ERR_DIRECTORY_NOT_EXIST]: 'ERR_DIRECTORY_NOT_EXIST',
  [ERR_DATABASE_LOCKED]: 'ERR_DATABASE_LOCKED',
  [ERR_DISK_SPACE_EXHAUSTED]: 'ERR_DISK_SPACE_EXHAUSTED',
  [ERR_CORRUPTION_DETECTED]: 'ERR_CORRUPTION_DETECTED',
  [ERR_INVALID_PATH]: 'ERR_INVALID_PATH',
  [ERR_CONFIG_INVALID]: 'ERR_CONFIG_INVALID',
  [ERR_INVALID_ARGUMENT]: 'ERR_INVALID_ARGUMENT',
  [ERR_NOT_FOUND]: 'ERR_NOT_FOUND',
  [ERR_NOT_SUPPORTED]: 'ERR_NOT_SUPPORTED',
  [ERR_INTERNAL_ERROR]: 'ERR_INTERNAL_ERROR',
  [ERR_ILLEGAL_OPERATION]: 'ERR_ILLEGAL_OPERATION',
  [ERR_IO_ERROR]: 'ERR_IO_ERROR',
  [ERR_BAD_ENCODING]: 'ERR_BAD_ENCODING',
  [ERR_INVALID_FILE]: 'ERR_INVALID_FILE',
  [ERR_EXTENSION]: 'ERR_EXTENSION',
  [ERR_NETWORK]: 'ERR_NETWORK',
  [ERR_SESSION_CLOSED]: 'ERR_SESSION_CLOSED',
  [ERR_CONNECTION_CLOSED]: 'ERR_CONNECTION_CLOSED',
  [ERR_POOL_EXHAUSTED]: 'ERR_POOL_EXHAUSTED',
  [ERR_SERVICE_UNAVAILABLE]: 'ERR_SERVICE_UNAVAILABLE',
  [ERR_LOAD_OVERFLOW]: 'ERR_LOAD_OVERFLOW',
  [ERR_CONNECTION_ERROR]: 'ERR_CONNECTION_ERROR',
  [ERR_COMPILATION]: 'ERR_COMPILATION',
  [ERR_QUERY_EXECUTION]: 'ERR_QUERY_EXECUTION',
  [ERR_QUERY_SYNTAX]: 'ERR_QUERY_SYNTAX',
  [ERR_QUERY_TIMEOUT]: 'ERR_QUERY_TIMEOUT',
  [ERR_CONCURRENT_WRITE]: 'ERR_CONCURRENT_WRITE',
  [ERR_CODEGEN_ERROR]: 'ERR_CODEGEN_ERROR',
  [ERR_EMPTY_RESULT]: 'ERR_EMPTY_RESULT',
  [ERR_NOT_INITIALIZED]: 'ERR_NOT_INITIALIZED',
  [ERR_TX_STATE_CONFLICT]: 'ERR_TX_STATE_CONFLICT',
  [ERR_WAL_WRITE_FAIL]: 'ERR_WAL_WRITE_FAIL',
  [ERR_TX_TIMEOUT]: 'ERR_TX_TIMEOUT',
  [ERR_SCHEMA_MISMATCH]: 'ERR_SCHEMA_MISMATCH',
  [ERR_INVALID_SCHEMA]: 'ERR_INVALID_SCHEMA',
  [ERR_TYPE_CONVERSION]: 'ERR_TYPE_CONVERSION',
  [ERR_TYPE_OVERFLOW]: 'ERR_TYPE_OVERFLOW',
  [ERR_INDEX_ERROR]: 'ERR_INDEX_ERROR',
  [ERR_PLATFORM_ABI]: 'ERR_PLATFORM_ABI',
  [ERR_PY_BIND_INIT]: 'ERR_PY_BIND_INIT',
  [ERR_ARCH_MISMATCH]: 'ERR_ARCH_MISMATCH',
  [ERR_DEPLOY_DEPENDENCY]: 'ERR_DEPLOY_DEPENDENCY',
  [ERR_NOT_IMPLEMENTED]: 'ERR_NOT_IMPLEMENTED',
  [ERR_UNKNOWN]: 'ERR_UNKNOWN',
};

/**
 * Get the name of an error code.
 * @param {number} code - The numeric error code.
 * @returns {string} The error code name, or 'ERR_UNKNOWN' if not found.
 */
function codeName(code) {
  return Code[code] || 'ERR_UNKNOWN';
}

module.exports = {
  // General errors
  OK,
  ERR_PERMISSION,
  ERR_VERSION_MISMATCHED,
  ERR_DIRECTORY_NOT_EXIST,
  ERR_DATABASE_LOCKED,
  ERR_DISK_SPACE_EXHAUSTED,
  ERR_CORRUPTION_DETECTED,
  ERR_INVALID_PATH,
  ERR_CONFIG_INVALID,
  ERR_INVALID_ARGUMENT,
  ERR_NOT_FOUND,
  ERR_NOT_SUPPORTED,
  ERR_INTERNAL_ERROR,
  ERR_ILLEGAL_OPERATION,
  ERR_IO_ERROR,
  ERR_BAD_ENCODING,
  ERR_INVALID_FILE,
  ERR_EXTENSION,
  // Network errors
  ERR_NETWORK,
  ERR_SESSION_CLOSED,
  ERR_CONNECTION_CLOSED,
  ERR_POOL_EXHAUSTED,
  ERR_SERVICE_UNAVAILABLE,
  ERR_LOAD_OVERFLOW,
  ERR_CONNECTION_ERROR,
  // Query errors
  ERR_COMPILATION,
  ERR_QUERY_EXECUTION,
  ERR_QUERY_SYNTAX,
  ERR_QUERY_TIMEOUT,
  ERR_CONCURRENT_WRITE,
  ERR_CODEGEN_ERROR,
  ERR_EMPTY_RESULT,
  ERR_NOT_INITIALIZED,
  // Transaction errors
  ERR_TX_STATE_CONFLICT,
  ERR_WAL_WRITE_FAIL,
  ERR_TX_TIMEOUT,
  // Schema errors
  ERR_SCHEMA_MISMATCH,
  ERR_INVALID_SCHEMA,
  ERR_TYPE_CONVERSION,
  ERR_TYPE_OVERFLOW,
  ERR_INDEX_ERROR,
  // Deployment errors
  ERR_PLATFORM_ABI,
  ERR_PY_BIND_INIT,
  ERR_ARCH_MISMATCH,
  ERR_DEPLOY_DEPENDENCY,
  // Not implemented
  ERR_NOT_IMPLEMENTED,
  // Unknown
  ERR_UNKNOWN,
  // Code enum (code → name)
  Code,
  codeName,
};
