// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_svc.proto

#include "http_svc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace server {
PROTOBUF_CONSTEXPR HttpRequest::HttpRequest(
    ::_pbi::ConstantInitialized) {}
struct HttpRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HttpRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HttpRequestDefaultTypeInternal() {}
  union {
    HttpRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HttpRequestDefaultTypeInternal _HttpRequest_default_instance_;
PROTOBUF_CONSTEXPR HttpResponse::HttpResponse(
    ::_pbi::ConstantInitialized) {}
struct HttpResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HttpResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HttpResponseDefaultTypeInternal() {}
  union {
    HttpResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HttpResponseDefaultTypeInternal _HttpResponse_default_instance_;
}  // namespace server
static ::_pb::Metadata file_level_metadata_http_5fsvc_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_http_5fsvc_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_http_5fsvc_2eproto[1];

const uint32_t TableStruct_http_5fsvc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::server::HttpRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::server::HttpResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::server::HttpRequest)},
  { 6, -1, -1, sizeof(::server::HttpResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::server::_HttpRequest_default_instance_._instance,
  &::server::_HttpResponse_default_instance_._instance,
};

const char descriptor_table_protodef_http_5fsvc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016http_svc.proto\022\006server\032\033google/protobu"
  "f/empty.proto\"\r\n\013HttpRequest\"\016\n\014HttpResp"
  "onse2\276\001\n\013HttpService\0226\n\006Schema\022\026.google."
  "protobuf.Empty\032\024.server.HttpResponse\022=\n\r"
  "ServiceStatus\022\026.google.protobuf.Empty\032\024."
  "server.HttpResponse\0228\n\013CypherQuery\022\023.ser"
  "ver.HttpRequest\032\024.server.HttpResponseB\003\200"
  "\001\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_http_5fsvc_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_http_5fsvc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_http_5fsvc_2eproto = {
    false, false, 290, descriptor_table_protodef_http_5fsvc_2eproto,
    "http_svc.proto",
    &descriptor_table_http_5fsvc_2eproto_once, descriptor_table_http_5fsvc_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_http_5fsvc_2eproto::offsets,
    file_level_metadata_http_5fsvc_2eproto, file_level_enum_descriptors_http_5fsvc_2eproto,
    file_level_service_descriptors_http_5fsvc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_http_5fsvc_2eproto_getter() {
  return &descriptor_table_http_5fsvc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_http_5fsvc_2eproto(&descriptor_table_http_5fsvc_2eproto);
namespace server {

// ===================================================================

class HttpRequest::_Internal {
 public:
};

HttpRequest::HttpRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:server.HttpRequest)
}
HttpRequest::HttpRequest(const HttpRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HttpRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:server.HttpRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HttpRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HttpRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HttpRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5fsvc_2eproto_getter, &descriptor_table_http_5fsvc_2eproto_once,
      file_level_metadata_http_5fsvc_2eproto[0]);
}

// ===================================================================

class HttpResponse::_Internal {
 public:
};

HttpResponse::HttpResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:server.HttpResponse)
}
HttpResponse::HttpResponse(const HttpResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HttpResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:server.HttpResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HttpResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HttpResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HttpResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_http_5fsvc_2eproto_getter, &descriptor_table_http_5fsvc_2eproto_once,
      file_level_metadata_http_5fsvc_2eproto[1]);
}

// ===================================================================

HttpService::~HttpService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* HttpService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_http_5fsvc_2eproto);
  return file_level_service_descriptors_http_5fsvc_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* HttpService::GetDescriptor() {
  return descriptor();
}

void HttpService::Schema(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::PROTOBUF_NAMESPACE_ID::Empty*,
                         ::server::HttpResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Schema() not implemented.");
  done->Run();
}

void HttpService::ServiceStatus(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::PROTOBUF_NAMESPACE_ID::Empty*,
                         ::server::HttpResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method ServiceStatus() not implemented.");
  done->Run();
}

void HttpService::CypherQuery(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::server::HttpRequest*,
                         ::server::HttpResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method CypherQuery() not implemented.");
  done->Run();
}

void HttpService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_http_5fsvc_2eproto[0]);
  switch(method->index()) {
    case 0:
      Schema(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::PROTOBUF_NAMESPACE_ID::Empty*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::server::HttpResponse*>(
                 response),
             done);
      break;
    case 1:
      ServiceStatus(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::PROTOBUF_NAMESPACE_ID::Empty*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::server::HttpResponse*>(
                 response),
             done);
      break;
    case 2:
      CypherQuery(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::server::HttpRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::server::HttpResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& HttpService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::PROTOBUF_NAMESPACE_ID::Empty::default_instance();
    case 1:
      return ::PROTOBUF_NAMESPACE_ID::Empty::default_instance();
    case 2:
      return ::server::HttpRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& HttpService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::server::HttpResponse::default_instance();
    case 1:
      return ::server::HttpResponse::default_instance();
    case 2:
      return ::server::HttpResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

HttpService_Stub::HttpService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
HttpService_Stub::HttpService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
HttpService_Stub::~HttpService_Stub() {
  if (owns_channel_) delete channel_;
}

void HttpService_Stub::Schema(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::PROTOBUF_NAMESPACE_ID::Empty* request,
                              ::server::HttpResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void HttpService_Stub::ServiceStatus(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::PROTOBUF_NAMESPACE_ID::Empty* request,
                              ::server::HttpResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void HttpService_Stub::CypherQuery(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::server::HttpRequest* request,
                              ::server::HttpResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace server
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::server::HttpRequest*
Arena::CreateMaybeMessage< ::server::HttpRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::server::HttpRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::server::HttpResponse*
Arena::CreateMaybeMessage< ::server::HttpResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::server::HttpResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
