#!/usr/bin/env python3

# Copyright 2020 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""For reproducing the compressed dictionaries embedded in the FTS extension.

python3 extension/fts/dict/compress_dict.py \
    third_party/cppjieba/test/testdata/extra_dict/jieba.dict.small.utf8 \
    extension/fts/dict/jieba_dict_small_zlib.inc kJiebaDictCompressed

python3 extension/fts/dict/compress_dict.py \
    third_party/cppjieba/dict/hmm_model.utf8 \
    extension/fts/dict/hmm_model_zlib.inc kHmmModelCompressed
"""

import argparse
import re
import zlib
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="dictionary to compress")
    parser.add_argument("output", type=Path, help="generated .inc file")
    parser.add_argument("symbol", help="C++ symbol for the compressed bytes")
    return parser.parse_args()


def make_include(symbol, original, compressed):
    lines = [
        "// Generated by dict/compress_dict.py.",
        f"constexpr unsigned char {symbol}[] = {{",
    ]
    for offset in range(0, len(compressed), 16):
        chunk = compressed[offset : offset + 16]
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines.extend(
        [
            "};",
            f"constexpr std::size_t {symbol}OriginalSize = {len(original)};",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    args = parse_args()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", args.symbol):
        raise ValueError(f"invalid C++ symbol: {args.symbol}")

    original = args.input.read_bytes()
    if not original:
        raise ValueError(f"input dictionary is empty: {args.input}")
    compressed = zlib.compress(original, level=9)
    args.output.write_text(
        make_include(args.symbol, original, compressed), encoding="ascii"
    )
    print(f"{args.input}: {len(original)} -> {len(compressed)} bytes")


if __name__ == "__main__":
    main()
