name: Build Wheels

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/build-wheel.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/build-wheel.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_wheels:
    runs-on: [self-hosted]
    strategy:
      matrix:
        os: [linux-x86_64]
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Only run install_dep.sh on macos system
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          bash scripts/install_deps.sh

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Prepare for macos
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET={{ env.MACOSX_DEPLOYMENT_TARGET }}"
          source ~/.graphscope_env
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Prepare for linux
        if: startsWith(matrix.os, 'linux')
        run: |
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV

      - name: Setup tmate session
        if: false
        uses: mxschmitt/action-tmate@v3

      - name: Build wheels
        run: |
          if [[ "${{matrix.os}}" == macos* ]]; then
            source ~/.graphscope_env
          fi
          export DEBUG=1
          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
          export BUILD_TYPE=RELEASE
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: (github.ref == 'refs/heads/main' && github.repository == 'GraphScope/neug') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'GraphScope/neug')
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
          verbose: true
          skip-existing: true # Skip existing wheels to avoid errors if the same wheel is already published, to update the wheel for a specific version, add -{number} to the filename and
          # update it manually
    
      # - name: cleanup runner workspace
      #   run: |
      #     echo $GITHUB_WORKSPACE
      #     rm -rf $GITHUB_WORKSPACE
      #     mkdir $GITHUB_WORKSPACE
      #   shell: bash
      #   if: ${{ failure() && steps.checkout.conclusion == 'failure' }}