name: Neug Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  # Comment out to save some actions minutes
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'cmake/**'
  #     - 'src/**'
  #     - 'proto/**'
  #     - '.github/workflows/python-test.yml'
  #     - 'third_party/**'
  #     - 'tools/python_bind/**'
  #     - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/neug-test.yml'
  push:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/neug-test.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-py-nexg:
    runs-on: [self-hosted]
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:v0.24.2-amd64-ccache
    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v3

    - name: Cache CCache
      if: false
      uses: actions/cache@v4
      with:
        path: ~/.cache
        # use timestamp as cache key to avoid cache miss
        key: ${{ runner.os }}-ccache-${{ github.run_id }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.run_id }}-
          ${{ runner.os }}-ccache-

    - name: Build Interactive
      run: |
        . /home/graphscope/.graphscope_env
        cd ${GITHUB_WORKSPACE}/
        git submodule update --init
        export DEBUG=1
        export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
        export BUILD_EXECUTABLES=ON
        export BUILD_TEST=ON
        export USE_NINJA=OFF
        # export CC="ccache gcc"
        # export CXX="ccache g++"
        cd tools/python_bind
        make requirements
        make build

    - name: Bulk Loader Test
      env:
        GS_TEST_DIR: ${{ github.workspace }}/gstest
      run: |
        git clone -b master --single-branch --depth=1 https://github.com/GraphScope/gstest.git ${GS_TEST_DIR}
        rm -rf /tmp/modern_graph && rm -rf /tmp/lsqb && rm -rf /tmp/ldbc && rm -rf /tmp/tinysnb
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        GLOG_v=10 ./build/nexg_py_bind/src/bin/bulk_loader -g ../../example_dataset/modern_graph/graph.yaml -l ../../example_dataset/modern_graph/import.yaml -d /tmp/modern_graph
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/lsqb-sf01
        GLOG_v=10 ./build/nexg_py_bind/src/bin/bulk_loader -g ../../example_dataset/lsqb-sf01/graph.yaml -l ../../example_dataset/lsqb-sf01/import.yaml -d /tmp/lsqb
        export FLEX_DATA_DIR=${GS_TEST_DIR}/flex/ldbc-sf01-long-date
        GLOG_v=10 ./build/nexg_py_bind/src/bin/bulk_loader -g ../../example_dataset/ldbc/graph.yaml -l ../../example_dataset/ldbc/import.yaml -d /tmp/ldbc/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/tinysnb
        GLOG_v=10 ./build/nexg_py_bind/src/bin/bulk_loader -g ../../example_dataset/tinysnb/graph.yaml -l ../../example_dataset/tinysnb/import.yaml -d /tmp/tinysnb

    - name: Run Python Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        pip3 install -r requirements_dev.txt
        python3 -m pytest -sv tests/test_batch_loading.py
        python3 -m pytest -sv tests/test_ddl.py


    - name: Run lsqb test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export LSQB_DATA_DIR=/tmp/lsqb
        python3 -m pytest -sv tests/test_lsqb.py

    - name: Run Gopt_planner_test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        GLOG_v=10 ./build/nexg_py_bind/tests/rt_mutable_graph/test_gopt_planner /tmp/test_gopt_planner

    - name: Run TinySNB Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        GLOG_v=10 ./build/nexg_py_bind/tests/rt_mutable_graph/test_run_query /tmp/tinysnb "MATCH (a:person)-[e1:knows]->(b:person) WHERE a.age > 35 RETURN b.fName"

    - name: Run DB Init Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # db tests
        python3 -m pytest -sv tests/test_db_init.py

    - name: Run DB Connection Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # db connection tests
        python3 -m pytest -sv tests/test_db_connection.py
      
    - name: Run Import/Export Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # import/export tests
        python3 -m pytest -sv tests/test_db_import_export.py

    - name: Run DDL Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # ddl tests
        python3 -m pytest -sv tests/test_db_query.py



