name: Neug Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  # Comment out to save some actions minutes
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'cmake/**'
  #     - 'src/**'
  #     - 'proto/**'
  #     - '.github/workflows/python-test.yml'
  #     - 'third_party/**'
  #     - 'tools/python_bind/**'
  #     - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/neug-test.yml'
      - 'scripts/install_deps.sh'
  push:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
      - '.github/workflows/neug-test.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-py-neug:
    runs-on: [self-hosted]
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:neug-dev
      # options: --user root
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Mark directory safe
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global --add safe.directory "$GITHUB_WORKSPACE/third_party/aliyun-oss-cpp-sdk"
        git config --global --add safe.directory "$GITHUB_WORKSPACE/third_party/parallel-hashmap"
        git config --global --add safe.directory "$GITHUB_WORKSPACE/third_party/pybind11"

    - name: Clean the tool directory for self-hosted runner
      run: |
        rm -rf /__w/_tool/Python

    - name: Cache CCache
      if: false
      uses: actions/cache@v4
      with:
        path: ~/.cache
        # use timestamp as cache key to avoid cache miss
        key: ${{ runner.os }}-ccache-${{ github.run_id }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.run_id }}-
          ${{ runner.os }}-ccache-

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Build Interactive
      run: |
        . /home/neug/.neug_env
        cd ${GITHUB_WORKSPACE}/
        export BUILD_TYPE=DEBUG
        export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
        export BUILD_EXECUTABLES=ON
        export BUILD_HTTP_SERVER=ON
        export BUILD_TEST=ON
        export USE_NINJA=OFF
        export WITH_MIMALLOC=ON
        export CMAKE_INSTALL_PREFIX=/opt/neug-install/
        sudo mkdir -p /opt/neug-install
        sudo chown -R $USER:$USER /opt/neug-install/
        # export CC="ccache gcc"
        # export CXX="ccache g++"
        cd tools/python_bind
        make clean
        make requirements
        make build

    - name: Bulk Loader Test
      env:
        GS_TEST_DIR: ${{ github.workspace }}/gstest
      run: |
        git clone -b master --single-branch --depth=1 https://github.com/GraphScope/gstest.git ${GS_TEST_DIR}
        rm -rf /tmp/modern_graph && rm -rf /tmp/lsqb && rm -rf /tmp/ldbc && rm -rf /tmp/tinysnb
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        GLOG_v=10 ./build/neug_py_bind/src/bin/bulk_loader -g ../../example_dataset/modern_graph/graph.yaml -l ../../example_dataset/modern_graph/import.yaml -d /tmp/modern_graph
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/lsqb-sf01
        GLOG_v=10 ./build/neug_py_bind/src/bin/bulk_loader -g ../../example_dataset/lsqb-sf01/graph.yaml -l ../../example_dataset/lsqb-sf01/import.yaml -d /tmp/lsqb
        export FLEX_DATA_DIR=${GS_TEST_DIR}/flex/ldbc-sf01-long-date
        GLOG_v=10 ./build/neug_py_bind/src/bin/bulk_loader -g ../../example_dataset/ldbc/graph.yaml -l ../../example_dataset/ldbc/import.yaml -d /tmp/ldbc/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/tinysnb
        GLOG_v=10 ./build/neug_py_bind/src/bin/bulk_loader -g ../../example_dataset/tinysnb/graph.yaml -l ../../example_dataset/tinysnb/import.yaml -d /tmp/tinysnb
    
    - name: Run C++ Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export MODERN_GRAPH_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        ctest -R storage_test -V

    - name: Run Python Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        pip3 install -r requirements_dev.txt
        python3 -m pytest -sv tests/test_batch_loading.py
        python3 -m pytest -sv tests/test_alter_property.py
        python3 -m pytest -sv tests/test_ddl.py
        export NEUG_DB_DIR=/tmp/tinysnb
        export NEUG_QUERY='MATCH (n1:person)-[:knows]-(n2:person)-[:knows]-(n3:person), (n1)-[:knows]-(n3) RETURN n1.fName, n2.fName, n3.fName'
        python3 -m pytest -sv tests/test_query.py
        export NEUG_DB_DIR=/tmp/modern_graph
        export NEUG_QUERY='MATCH (n1:person)-[:knows]-(n2:person)-[:knows]-(n3:person), (n1)-[:knows]-(n3) RETURN n1.name, n2.name, n3.name'
        python3 -m pytest -sv tests/test_query.py
        python3 -m pytest -sv tests/test_tp_service.py


    - name: Run lsqb test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export LSQB_DATA_DIR=/tmp/lsqb
        python3 -m pytest -sv tests/test_lsqb.py

    - name: Run TinySNB Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        GLOG_v=10 ./build/neug_py_bind/tests/unittest/test_run_query /tmp/tinysnb "MATCH (a:person)-[e1:knows]->(b:person) WHERE a.age > 35 RETURN b.fName"

    - name: Run DB Init Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # db tests
        python3 -m pytest -sv tests/test_db_init.py

    - name: Run DB Connection Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # db connection tests
        python3 -m pytest -sv tests/test_db_connection.py

    - name: Run Query Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # ddl & dml & query tests
        python3 -m pytest -sv tests/test_db_query.py
        python3 -m pytest -sv tests/test_dataset.py

    - name: Run Transaction Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # import/export tests
        python3 -m pytest -sv tests/test_db_transaction.py
      
    - name: Run Import/Export Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # import/export tests
        python3 -m pytest -sv tests/test_db_import_export.py

    - name: Run List Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        # list tests
        python3 -m pytest -sv tests/test_db_list.py

    - name: Run IC Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export LDBC_DATA_DIR=/tmp/ldbc
        python3 -m pytest -sv tests/test_ic.py

    - name: Run E2E Cypher Test
      run: |
        cd ${GITHUB_WORKSPACE}/tests/e2e
        # e2e cypher tests
        # 1. tests running on modern_graph
        ./scripts/run_embed_test.sh modern_graph /tmp/modern_graph basic_test
        # 2. tests running on tinysnb
        # all tinysnb cypher queries is included except some marked issues (TODO: shaoyu)
        # ./scripts/run_embed_test.sh tinysnb /tmp/tinysnb basic_test,projection,filter,order_by,expr,acc,agg,match,cyclic,arithmetic
        # ./scripts/run_embed_test.sh tinysnb /tmp/tinysnb batch_delete_vertices true
        # ./scripts/run_embed_test.sh tinysnb /tmp/tinysnb batch_delete_edges true

    - name: Run E2E tinysnb Test
      run: |
        cd ${GITHUB_WORKSPACE}/tests/e2e
        # in convenience, we use "read-write" model to run all test cases together
        ./scripts/run_embed_test.sh tinysnb /tmp/tinysnb "" true

    - name: Run E2E LSQB Test
      run: |
        cd ${GITHUB_WORKSPACE}/tests/e2e
        ./scripts/run_embed_test.sh lsqb /tmp/lsqb lsqb
    
    - name: Run E2E LDBC Test
      run: |
        cd ${GITHUB_WORKSPACE}/tests/e2e
        ./scripts/run_embed_test.sh ldbc /tmp/ldbc agg,match

    - name: Run E2E LDBC Test
      run: |
        cd ${GITHUB_WORKSPACE}/tests/e2e
        ./scripts/run_embed_test.sh ldbc /tmp/ldbc agg,match,ldbc

    - name: Test installation c++ sdk
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/build/neug_py_bind
        sudo make install
        ldd /opt/neug-install/lib/libneug_libraries.so
        printenv
        cd  ${GITHUB_WORKSPACE}/tests/test_cpp_installation
        mkdir build && cd build
        export CMAKE_PREFIX_PATH=/opt/neug/:/opt/neug-install/
        cmake .. && make -j1
        ./test

    # - name: Run E2E LSQB Benchmark
    #   run: |
    #     cd ${GITHUB_WORKSPACE}/tests/e2e
    #     # run lsqb benchmark
    #     python3 -m pytest -m neug_benchmark --db_dir=/tmp/lsqb/ --query_dir=./queries/lsqb/ --dataset lsqb --iterations 1 --rounds 1 --read_only --benchmark-save=benchmark-lsqb

    - name: Build CLI tool
      run: |
        cd ${GITHUB_WORKSPACE}/tools/shell/
        pip3 install .

    - name: Test CLI tool
      run: |
        cd ${GITHUB_WORKSPACE}/tools/shell/tests/
        # test ngcli commands
        python3 -m pytest -sv test_ngcli_commands.py
        # test ngcli shell
        python3 -m pytest -sv test_ngcli_basics.py
