name: Nexg Python Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - '.github/workflows/python-test.yml'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - '.github/workflows/python-test.yml'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/**'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-py-nexg:
    runs-on: ubuntu-22.04
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:v0.24.2-amd64
    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v3

    - name: Build Interactive
      run: |
        . /home/graphscope/.graphscope_env
        cd ${GITHUB_WORKSPACE}/
        git submodule update --init
        export BUILD_EXECUTABLES=ON
        export DEBUG=1
        export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
        cd tools/python_bind
        make build


    - name: Run Python Test
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        export FLEX_DATA_DIR=${GITHUB_WORKSPACE}/example_dataset/modern_graph
        pip3 install -r requirements_dev.txt
        python3 -m pytest -v tests/test_batch_loading.py


