name: Nexg Python Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'cmake/**'
      - 'src/**'
      - 'proto/**'
      - '.github/workflows/python-test.yml'
      - 'third_party/**'
      - 'tools/python_bind/**'
      - 'tests/'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-py-nexg:
    runs-on: ubuntu-22.04
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:v0.24.2-amd64
    steps:
    - uses: actions/checkout@v4

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v3

    - name: Build Interactive
      run: |
        . /home/graphscope/.graphscope_env
        cd ${GITHUB_WORKSPACE}/
        git submodule update --init
        export BUILD_EXECUTABLES=ON
        export DEBUG=1
        cd tools/python_bind
        make build

    - name: Prepare dataset and workspace
      env:
        MODERN_GRAPH_DB_DIR: /tmp/modern_graph
      run: |
        mkdir -p ${MODERN_GRAPH_DB_DIR}
        export FLEX_DATA_DIR=../example_dataset/modern_graph
        cd ${GITHUB_WORKSPACE}/tools/python_bind/build/nexg_py_bind
        GLOG_v=10 ./src/bin/bulk_loader -g ${INTERACTIVE_WORKSPACE}/data/modern_graph/graph.yaml -l ../example_dataset/modern_graph/bulk_load.yaml -d ${MODERN_GRAPH_DB_DIR}
    
    - name: Run Python Test
      env:
       MODERN_GRAPH_DB_DIR: /tmp/modern_graph
      run: |
        cd ${GITHUB_WORKSPACE}/tools/python_bind/
        python3 -m pytest -v tests/test_query.py


