# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import basic_type_pb2 as basic__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="schema.proto",
    package="schema",
    syntax="proto3",
    serialized_options=b"\n!com.alibaba.graphscope.gaia.protoB\013OuterSchema",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cschema.proto\x12\x06schema\x1a\x0c\x63ommon.proto\x1a\x10\x62\x61sic_type.proto"%\n\tLabelMeta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t"i\n\nColumnMeta\x12\x1e\n\x03key\x18\x01 \x01(\x0b\x32\x11.schema.LabelMeta\x12#\n\tdata_type\x18\x02 \x01(\x0b\x32\x10.common.DataType\x12\x16\n\x0eis_primary_key\x18\x03 \x01(\x08"S\n\nEntityMeta\x12 \n\x05label\x18\x01 \x01(\x0b\x32\x11.schema.LabelMeta\x12#\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x12.schema.ColumnMeta"\xd8\x01\n\x0cRelationMeta\x12 \n\x05label\x18\x01 \x01(\x0b\x32\x11.schema.LabelMeta\x12\x34\n\x0c\x65ntity_pairs\x18\x02 \x03(\x0b\x32\x1e.schema.RelationMeta.LabelPair\x12#\n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x12.schema.ColumnMeta\x1aK\n\tLabelPair\x12\x1e\n\x03src\x18\x01 \x01(\x0b\x32\x11.schema.LabelMeta\x12\x1e\n\x03\x64st\x18\x02 \x01(\x0b\x32\x11.schema.LabelMeta"\x82\x01\n\x06Schema\x12$\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x12.schema.EntityMeta\x12\'\n\trelations\x18\x02 \x03(\x0b\x32\x14.schema.RelationMeta\x12\x13\n\x0bis_table_id\x18\x03 \x01(\x08\x12\x14\n\x0cis_column_id\x18\x04 \x01(\x08\x42\x30\n!com.alibaba.graphscope.gaia.protoB\x0bOuterSchemab\x06proto3',
    dependencies=[
        common__pb2.DESCRIPTOR,
        basic__type__pb2.DESCRIPTOR,
    ],
)


_LABELMETA = _descriptor.Descriptor(
    name="LabelMeta",
    full_name="schema.LabelMeta",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="schema.LabelMeta.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="schema.LabelMeta.name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=56,
    serialized_end=93,
)


_COLUMNMETA = _descriptor.Descriptor(
    name="ColumnMeta",
    full_name="schema.ColumnMeta",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="schema.ColumnMeta.key",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="data_type",
            full_name="schema.ColumnMeta.data_type",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_primary_key",
            full_name="schema.ColumnMeta.is_primary_key",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=95,
    serialized_end=200,
)


_ENTITYMETA = _descriptor.Descriptor(
    name="EntityMeta",
    full_name="schema.EntityMeta",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="schema.EntityMeta.label",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="columns",
            full_name="schema.EntityMeta.columns",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=202,
    serialized_end=285,
)


_RELATIONMETA_LABELPAIR = _descriptor.Descriptor(
    name="LabelPair",
    full_name="schema.RelationMeta.LabelPair",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="src",
            full_name="schema.RelationMeta.LabelPair.src",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="dst",
            full_name="schema.RelationMeta.LabelPair.dst",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=429,
    serialized_end=504,
)

_RELATIONMETA = _descriptor.Descriptor(
    name="RelationMeta",
    full_name="schema.RelationMeta",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="schema.RelationMeta.label",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="entity_pairs",
            full_name="schema.RelationMeta.entity_pairs",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="columns",
            full_name="schema.RelationMeta.columns",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _RELATIONMETA_LABELPAIR,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=288,
    serialized_end=504,
)


_SCHEMA = _descriptor.Descriptor(
    name="Schema",
    full_name="schema.Schema",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="entities",
            full_name="schema.Schema.entities",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="relations",
            full_name="schema.Schema.relations",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_table_id",
            full_name="schema.Schema.is_table_id",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_column_id",
            full_name="schema.Schema.is_column_id",
            index=3,
            number=4,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=507,
    serialized_end=637,
)

_COLUMNMETA.fields_by_name["key"].message_type = _LABELMETA
_COLUMNMETA.fields_by_name["data_type"].message_type = basic__type__pb2._DATATYPE
_ENTITYMETA.fields_by_name["label"].message_type = _LABELMETA
_ENTITYMETA.fields_by_name["columns"].message_type = _COLUMNMETA
_RELATIONMETA_LABELPAIR.fields_by_name["src"].message_type = _LABELMETA
_RELATIONMETA_LABELPAIR.fields_by_name["dst"].message_type = _LABELMETA
_RELATIONMETA_LABELPAIR.containing_type = _RELATIONMETA
_RELATIONMETA.fields_by_name["label"].message_type = _LABELMETA
_RELATIONMETA.fields_by_name["entity_pairs"].message_type = _RELATIONMETA_LABELPAIR
_RELATIONMETA.fields_by_name["columns"].message_type = _COLUMNMETA
_SCHEMA.fields_by_name["entities"].message_type = _ENTITYMETA
_SCHEMA.fields_by_name["relations"].message_type = _RELATIONMETA
DESCRIPTOR.message_types_by_name["LabelMeta"] = _LABELMETA
DESCRIPTOR.message_types_by_name["ColumnMeta"] = _COLUMNMETA
DESCRIPTOR.message_types_by_name["EntityMeta"] = _ENTITYMETA
DESCRIPTOR.message_types_by_name["RelationMeta"] = _RELATIONMETA
DESCRIPTOR.message_types_by_name["Schema"] = _SCHEMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelMeta = _reflection.GeneratedProtocolMessageType(
    "LabelMeta",
    (_message.Message,),
    {
        "DESCRIPTOR": _LABELMETA,
        "__module__": "schema_pb2",
        # @@protoc_insertion_point(class_scope:schema.LabelMeta)
    },
)
_sym_db.RegisterMessage(LabelMeta)

ColumnMeta = _reflection.GeneratedProtocolMessageType(
    "ColumnMeta",
    (_message.Message,),
    {
        "DESCRIPTOR": _COLUMNMETA,
        "__module__": "schema_pb2",
        # @@protoc_insertion_point(class_scope:schema.ColumnMeta)
    },
)
_sym_db.RegisterMessage(ColumnMeta)

EntityMeta = _reflection.GeneratedProtocolMessageType(
    "EntityMeta",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENTITYMETA,
        "__module__": "schema_pb2",
        # @@protoc_insertion_point(class_scope:schema.EntityMeta)
    },
)
_sym_db.RegisterMessage(EntityMeta)

RelationMeta = _reflection.GeneratedProtocolMessageType(
    "RelationMeta",
    (_message.Message,),
    {
        "LabelPair": _reflection.GeneratedProtocolMessageType(
            "LabelPair",
            (_message.Message,),
            {
                "DESCRIPTOR": _RELATIONMETA_LABELPAIR,
                "__module__": "schema_pb2",
                # @@protoc_insertion_point(class_scope:schema.RelationMeta.LabelPair)
            },
        ),
        "DESCRIPTOR": _RELATIONMETA,
        "__module__": "schema_pb2",
        # @@protoc_insertion_point(class_scope:schema.RelationMeta)
    },
)
_sym_db.RegisterMessage(RelationMeta)
_sym_db.RegisterMessage(RelationMeta.LabelPair)

Schema = _reflection.GeneratedProtocolMessageType(
    "Schema",
    (_message.Message,),
    {
        "DESCRIPTOR": _SCHEMA,
        "__module__": "schema_pb2",
        # @@protoc_insertion_point(class_scope:schema.Schema)
    },
)
_sym_db.RegisterMessage(Schema)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
