# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import basic_type_pb2 as basic__type__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="type.proto",
    package="common",
    syntax="proto3",
    serialized_options=b"\n!com.alibaba.graphscope.gaia.protoB\010DataType",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\ntype.proto\x12\x06\x63ommon\x1a\x0c\x63ommon.proto\x1a\x10\x62\x61sic_type.proto\x1a\x1egoogle/protobuf/wrappers.proto"\x9f\x04\n\rGraphDataType\x12:\n\x0b\x65lement_opt\x18\x01 \x01(\x0e\x32%.common.GraphDataType.GraphElementOpt\x12?\n\x0fgraph_data_type\x18\x02 \x03(\x0b\x32&.common.GraphDataType.GraphElementType\x1a\x82\x01\n\x11GraphElementLabel\x12\r\n\x05label\x18\x01 \x01(\x05\x12.\n\tsrc_label\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\tdst_label\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x1aZ\n\x15GraphElementTypeField\x12!\n\x07prop_id\x18\x01 \x01(\x0b\x32\x10.common.NameOrId\x12\x1e\n\x04type\x18\x02 \x01(\x0b\x32\x10.common.DataType\x1a\x86\x01\n\x10GraphElementType\x12\x36\n\x05label\x18\x01 \x01(\x0b\x32\'.common.GraphDataType.GraphElementLabel\x12:\n\x05props\x18\x02 \x03(\x0b\x32+.common.GraphDataType.GraphElementTypeField"\'\n\x0fGraphElementOpt\x12\n\n\x06VERTEX\x10\x00\x12\x08\n\x04\x45\x44GE\x10\x01"h\n\nIrDataType\x12%\n\tdata_type\x18\x01 \x01(\x0b\x32\x10.common.DataTypeH\x00\x12+\n\ngraph_type\x18\x02 \x01(\x0b\x32\x15.common.GraphDataTypeH\x00\x42\x06\n\x04typeB-\n!com.alibaba.graphscope.gaia.protoB\x08\x44\x61taTypeb\x06proto3',
    dependencies=[
        common__pb2.DESCRIPTOR,
        basic__type__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,
    ],
)


_GRAPHDATATYPE_GRAPHELEMENTOPT = _descriptor.EnumDescriptor(
    name="GraphElementOpt",
    full_name="common.GraphDataType.GraphElementOpt",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="VERTEX",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="EDGE",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=591,
    serialized_end=630,
)
_sym_db.RegisterEnumDescriptor(_GRAPHDATATYPE_GRAPHELEMENTOPT)


_GRAPHDATATYPE_GRAPHELEMENTLABEL = _descriptor.Descriptor(
    name="GraphElementLabel",
    full_name="common.GraphDataType.GraphElementLabel",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="common.GraphDataType.GraphElementLabel.label",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="src_label",
            full_name="common.GraphDataType.GraphElementLabel.src_label",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="dst_label",
            full_name="common.GraphDataType.GraphElementLabel.dst_label",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=230,
    serialized_end=360,
)

_GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD = _descriptor.Descriptor(
    name="GraphElementTypeField",
    full_name="common.GraphDataType.GraphElementTypeField",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="prop_id",
            full_name="common.GraphDataType.GraphElementTypeField.prop_id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="type",
            full_name="common.GraphDataType.GraphElementTypeField.type",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=362,
    serialized_end=452,
)

_GRAPHDATATYPE_GRAPHELEMENTTYPE = _descriptor.Descriptor(
    name="GraphElementType",
    full_name="common.GraphDataType.GraphElementType",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="common.GraphDataType.GraphElementType.label",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="props",
            full_name="common.GraphDataType.GraphElementType.props",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=455,
    serialized_end=589,
)

_GRAPHDATATYPE = _descriptor.Descriptor(
    name="GraphDataType",
    full_name="common.GraphDataType",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="element_opt",
            full_name="common.GraphDataType.element_opt",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="graph_data_type",
            full_name="common.GraphDataType.graph_data_type",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _GRAPHDATATYPE_GRAPHELEMENTLABEL,
        _GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD,
        _GRAPHDATATYPE_GRAPHELEMENTTYPE,
    ],
    enum_types=[
        _GRAPHDATATYPE_GRAPHELEMENTOPT,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=87,
    serialized_end=630,
)


_IRDATATYPE = _descriptor.Descriptor(
    name="IrDataType",
    full_name="common.IrDataType",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="data_type",
            full_name="common.IrDataType.data_type",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="graph_type",
            full_name="common.IrDataType.graph_type",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="type",
            full_name="common.IrDataType.type",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=632,
    serialized_end=736,
)

_GRAPHDATATYPE_GRAPHELEMENTLABEL.fields_by_name["src_label"].message_type = (
    google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
)
_GRAPHDATATYPE_GRAPHELEMENTLABEL.fields_by_name["dst_label"].message_type = (
    google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
)
_GRAPHDATATYPE_GRAPHELEMENTLABEL.containing_type = _GRAPHDATATYPE
_GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD.fields_by_name["prop_id"].message_type = (
    common__pb2._NAMEORID
)
_GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD.fields_by_name["type"].message_type = (
    basic__type__pb2._DATATYPE
)
_GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD.containing_type = _GRAPHDATATYPE
_GRAPHDATATYPE_GRAPHELEMENTTYPE.fields_by_name["label"].message_type = (
    _GRAPHDATATYPE_GRAPHELEMENTLABEL
)
_GRAPHDATATYPE_GRAPHELEMENTTYPE.fields_by_name["props"].message_type = (
    _GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD
)
_GRAPHDATATYPE_GRAPHELEMENTTYPE.containing_type = _GRAPHDATATYPE
_GRAPHDATATYPE.fields_by_name["element_opt"].enum_type = _GRAPHDATATYPE_GRAPHELEMENTOPT
_GRAPHDATATYPE.fields_by_name["graph_data_type"].message_type = (
    _GRAPHDATATYPE_GRAPHELEMENTTYPE
)
_GRAPHDATATYPE_GRAPHELEMENTOPT.containing_type = _GRAPHDATATYPE
_IRDATATYPE.fields_by_name["data_type"].message_type = basic__type__pb2._DATATYPE
_IRDATATYPE.fields_by_name["graph_type"].message_type = _GRAPHDATATYPE
_IRDATATYPE.oneofs_by_name["type"].fields.append(
    _IRDATATYPE.fields_by_name["data_type"]
)
_IRDATATYPE.fields_by_name["data_type"].containing_oneof = _IRDATATYPE.oneofs_by_name[
    "type"
]
_IRDATATYPE.oneofs_by_name["type"].fields.append(
    _IRDATATYPE.fields_by_name["graph_type"]
)
_IRDATATYPE.fields_by_name["graph_type"].containing_oneof = _IRDATATYPE.oneofs_by_name[
    "type"
]
DESCRIPTOR.message_types_by_name["GraphDataType"] = _GRAPHDATATYPE
DESCRIPTOR.message_types_by_name["IrDataType"] = _IRDATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphDataType = _reflection.GeneratedProtocolMessageType(
    "GraphDataType",
    (_message.Message,),
    {
        "GraphElementLabel": _reflection.GeneratedProtocolMessageType(
            "GraphElementLabel",
            (_message.Message,),
            {
                "DESCRIPTOR": _GRAPHDATATYPE_GRAPHELEMENTLABEL,
                "__module__": "type_pb2",
                # @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementLabel)
            },
        ),
        "GraphElementTypeField": _reflection.GeneratedProtocolMessageType(
            "GraphElementTypeField",
            (_message.Message,),
            {
                "DESCRIPTOR": _GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD,
                "__module__": "type_pb2",
                # @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementTypeField)
            },
        ),
        "GraphElementType": _reflection.GeneratedProtocolMessageType(
            "GraphElementType",
            (_message.Message,),
            {
                "DESCRIPTOR": _GRAPHDATATYPE_GRAPHELEMENTTYPE,
                "__module__": "type_pb2",
                # @@protoc_insertion_point(class_scope:common.GraphDataType.GraphElementType)
            },
        ),
        "DESCRIPTOR": _GRAPHDATATYPE,
        "__module__": "type_pb2",
        # @@protoc_insertion_point(class_scope:common.GraphDataType)
    },
)
_sym_db.RegisterMessage(GraphDataType)
_sym_db.RegisterMessage(GraphDataType.GraphElementLabel)
_sym_db.RegisterMessage(GraphDataType.GraphElementTypeField)
_sym_db.RegisterMessage(GraphDataType.GraphElementType)

IrDataType = _reflection.GeneratedProtocolMessageType(
    "IrDataType",
    (_message.Message,),
    {
        "DESCRIPTOR": _IRDATATYPE,
        "__module__": "type_pb2",
        # @@protoc_insertion_point(class_scope:common.IrDataType)
    },
)
_sym_db.RegisterMessage(IrDataType)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
